specifications/xpath-functions-40/src/function-catalog.xml
Spec identifiers are case sensitive.
=> Fix typo in spec reference

.circleci/config.yml
The CI script shouldn't attempt to upgrade the host. CircleCI have customized some of the packages so upgrading doesn't work. And it shouldn't really be necessary anyway.
=> Don't attempt to upgrade the host

build.gradle
The XSLT 4.0 spec didn't build correctly because the input paths in the build script were missing the /specification/ directory :-(
=> Fix error in input paths for XSLT

specifications/xpath-functions-40/style/xpath-functions.xsl
1. Determine which functions cannot be resolved and disable them in the pull down
2. Adjust the CSS so that the function finder doesn't scroll out-of-view
=> Fix the function finder

.github/workflows/build-specs.yml, build.gradle, specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Recent changes (#184) from MK have added a new automatically generated test to the F&O build.
This PR automates the construction and publication of new test sets from the `qtspecs` repository to the `qt4stests` repository.
N.B. The repository where tests are published (`qt4cg/qt4tests` in this case) must be the value of the TEST_REPOSITORY secret. If you want to automate publication to your own fork, just set the value of that secret accordingly.
=> Update build automation to publish tests

specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Modify the generated test set to use a real source file. The source/content construct for inline documents works in the XSLT test suite but not in QT4.
=> Modify test generator to reference a real source file

specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
This PR is intended to be technically equivalent to #185.
I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them. 
Close #119
=> NW for MK: Drop xsl:match instruction (185)

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Drops the proposed map:group-by function, replacing it with the more powerful map:build.
=> Issue 151: map:build

specifications/xpath-functions-40/style/merge-function-specs.xsl
This PR formats `eg` in `fos:expression` and `fos:result` as a block. I don't think this will have any detrimental effects as it's done during the "merging" process.
=> Allow eg in fos:expression and fos:result

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/generate-keyword-test-set.xsl, specifications/xpath-functions-40/style/xpath-functions.xsl, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/conformance.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/introduction.xml, specifications/xquery-40/src/mime-type.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xquery-40/src/xpath-backwards-compat.xml, specifications/xquery-40/src/xquery-header.xml, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/function-catalog.xml, specifications/xslt-40/src/xslt.xml
This PR is intended to be technically equivalent to #166.
I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them.
=> NW for MK: Variadicity (166)

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl, specifications/xpath-functions-40/style/xpath-functions.xsl, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
Close #72 
This is a first attempt to resolve issue 72 by describing `parse-uri` and `build-uri` functions.
I decided to try an approach that leverages the ABNF defined in RFC 3986. Attempting to redefine the rules just opens up the possibility that the rules we write will differ from the rules in RFC 3986 which would be wrong.
I added an options map and specified a "details" option that will further parse the path and query components. This gives the caller easy access to the percent-decoded forms of those elements without making the parse function irreversable.
Notes:
1. More examples are needed
2. I tried to use `eg` in the results so that they'd be formatted nicely, but it didn't work. Is there any markup for verbatim text in examples?
3. There's an open question about whether …
=> First attempt at parse-uri and build-uri functions

specifications/xquery-40/src/expressions.xml
The discussion on issue 71 was very wide-ranging and went off into a number of tangents. This PR attempts to resolve the issue initially raised (order of evaluation of predicates) in a general way by introducing the notion of guarded expressions. This also provides a proposed solution to the question of "short-cutting" and/or expressions - essentially, an optimiser can change the order of evaluation, but doing so must not introduce dynamic errors that would not occur in a short-cutted evaluation.
=> New proposed text resolving issue 71 (Guarded expressions)

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/xpath-backwards-compat.xml
This PR is purely editorial: it updates change logs and status information to reflect the current state of play. In particular, the change logs in appendices now attempt to distinguish changes approved by the WG from changes that were in the baseline draft prepared by the editor, but which have not yet been reviewed or approved.
=> Editorial: update change logs and status

.github/workflows/build-pr.yml
Letting the specification-specific XSL through means you can get a mismatch with the common XSL. So don't do that.
=> Exclude spec XSL from PRs

build.gradle
Fix #255 
Repeat after me, "filenames are not URIs." Not on some platforms, anyway.
I still get a warning about "correctness" because of the interaction between a couple of tasks. That doesn't happen on a *nix platform so I don't know if it's related to the difference between forward and backward slashes or if it's a consequence of the build changes I made to support the new SVG (that might be) in data model. They seem harmless for the moment.
=> Make './gradlew publish' work on Windows #255

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/function-catalog.xml, specifications/xslt-40/src/xslt.xml, style/extract.xsl
This PR fixes issue #270 concerning the visibility of XSLT modes.
It also deals with a lot of editorial issues, some highlighted in issue #275.
It changes the manual change markup in the XSLT spec to use `at-"date"` format rather than `at="draft-number"` (dates are more useful for the incremental development process we are following). And it fixes some cross-spec-reference issues, and some violations of hyphenation diktats.
Also bundled with this bug fix are other editorial changes to fix cross-spec linking errors; for details see the individual commit messages.
=> Issue270 xslt mode visibility

specifications/xpath-functions-40/src/function-catalog.xml
Changes to the new fn:char function (issue #121) as follows:
- Action QT4CG-017-01 clarifies the definition of formats #nnn and #xnnn.
- Action QT4CG-017-02 changes the order of the rules
- In discussion it was asked whether any HTML5 entity names refer to strings comprising more than one character. On investigation it appears that they do, and the spec has been revised to allow for this.
- added history/status information
=> fn:char - editors actions from 2023-01-10

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-examples.xml
As discussed in issue #234. In reviewing this PR, I suggest we consider it together with the existing proposals for ternary conditionals (x ?? y !! z) and the "otherwise" operator.
=> Add grammar for "if (test) then {expr}" with no else

specifications/xpath-functions-40/src/function-catalog.xml
Allow remove() to remove several items, aligning it with array:remove() and map:remove()
=> Issue 294: fn:remove()

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
We agreed today to drop ternary conditional expressions from the proposal; this PR implements that change.
=> Drop ternary conditionals, as agreed on 2023-01-17

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
See issue #58.
I would recommend reviewing the XQuery version of the spec first, since it contains additional notes contrasting string templates and the existing string constructors. The section on string constructors has moved, but is unchanged except for the addition of this note.
=> Proposed syntax and semantics for string templates

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
This PR applies the following review comments:
=> Update fn:parse-html to apply review feedback.

specifications/xpath-functions-40/style/xpath-functions.xsl
Record types are better supported by the stylesheets so the dagger is simply a distraction.
=> Remove dagger from record cross-references

.github/workflows/build-pr.yml
This PR changes the CI `build-pr.yml` script so that it checks out the version of master that the branch started from, rather than the current version of master, for building the specifications.
* Pro: we won't get build failures when the current master can't build the old version (for example, when images have been removed)
* Con: we won't get any features from the current master, such as stylesheet updates
Since failing builds are more troublesome than formatting issues, I'm going to say the pros outweigh the cons.
=> Attempt to build PR with merge-base version of master

specifications/xslt-40/src/function-catalog.xml
This PR addresses issue 69, by modifying those XSLT built-in functions that currently have multiple signatures, to use a single signature with parameter defaults instead.
The changes however don't currently render correctly. The XSLT processing pipeline needs to be changed to pick up the changes that were made to the F+O stylesheets to render parameter defaults correctly. I haven't yet managed to work out where this is done.
=> Combine multiple signatures of XSLT functions to use defaults

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/expressions.xml
Fix #377 
I took a minimal approach here. I've removed CDATA sections where the section contained an `&` but not a `<`.
1. If the section contains `<`, then it's  (presumably) necessary to escape the markup
2. If the section *does not* contain an `&`, then it's irrelevant. But not removing it limits the number of places changed by the script
=> Removed CDATA sections around markup

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Addresses the proposal in issue 22 to allow repetition of the "let" or "for" keyword in a ForExpr or LetExpr. (It does not, however, allow "for" and "let" to be mixed).
=> Issue 22: allow "for"/"let" keyword to be repeated in XPath

specifications/css/xslt-xquery-serialization-40.css
This PR completes my action to fix the dark blue background in examples in the serialization spec. I've made them the same as the examples in the XSLT spec which seem to have been satisfactory.
=> Update the example background color in serialization

specifications/xpath-functions-40/src/function-catalog.xml
This proposal adds an options parameter to fn:deep-equal, giving much more detailed control over how the comparison is performed (while remaining backwards compatible by default).
This proposal is a first draft and I would request careful review, it's not one to pass through "on the nod".
=> Issue 98 - add options parameter to fn:deep-equal

specifications/xpath-functions-40/src/xpath-functions.xml
This PR applies the following changes:
=> Update the localName and unparsed entity reference notes for parse-html

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml
This PR is purely editorial in the sense that it does not attempt to make any changes that would affect an implementation. It's intended to clear up ambiguity and lack of clarity in the description of operations on functions, in particular the way that a function item captures static and dynamic context. It addresses issues #239 and issue #392.
=> Clarify explanations of functions/function items

specifications/xpath-functions-40/src/function-catalog.xml
The `fn:parse-uri()` function recognizes "URIs" of the form `c:/path/to/thing` as implicitly being `file:` URIs. This small change adds a leading "/" to make the fact that it is a path explicit.
=> Minor correction to fn:parse-uri

specifications/xpath-functions-40/src/function-catalog.xml
The `fn:parse-uri` function will parse hierarchical or non-hierarchical URIs, however, the parse cannot be reversed if the `fn:build-uri` function doesn't know whether the scheme is hierarchical. Consider `fn:parse-uri("querty:abc")`:
```
map {
"path":"abc",
"scheme":"querty",
"path-segments":["abc"],
"uri":"querty:abc"
}
```
When `fn:build-uri` parses that map, it produces: `querty://abc` because the scheme is not known to be non-hierarchical.
This PR changes `fn:parse-uri` so that it records whether or not the URI was hierarchical and `fn:build-uri` to use that information.
It's possible that we could finesse this by setting the `authority` to the empty string for hierarchical URIs, but it seems clearer to be explicit.
This PR also fixes a bug. Previously, if the `scheme` was not …
=> Make the (non-)hierarchical nature of URIs explicit

specifications/grammar-40/xpath-grammar.xml, specifications/xslt-40/src/xslt.xml
Proposes how to handle type-based match patterns (record tests, in particular) in the absence of explicit priorities, basing the decision on the type hierarchy. Note: user-defined priorities are always considered before any inferred selectivity rules. Also fixes some grammar problems with type patterns. See Issue #400.
=> Issue 400: ranking of type patterns

specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
This PR revises the design of the xsl:array instruction to align it with the recently agreed specs for the functions `array:members` and `array:of`. The `composite` attribute and the `xsl:array-member` instruction are dropped; instead the instruction takes a `use` attribute which is an expression used to compute each array member value from the corresponding item in the value of the select expression or sequence constructor.
=> Revise xsl:array instruction and examples

specifications/xpath-functions-40/src/xpath-functions.xml
This applies the review action:
> RD to remove the note in 15.5.15 of functions and operators.
=> Remove the note from the parse-html unparsed-entity sections.

specifications/xslt-40/style/convert-grammar.xsl, style/extract.xsl, style/xmlspec-override.xsl, style/xsl-query-2016.xsl
Close #428
Hi @michaelhkay . I took a slightly different approach. For unknown reasons long since lost in the mists of time the 'etc' files that act as databases for cross-spec references stored `nt` elements. That's weird because the `nt` elements are supposed to point to `prod` elements. I expect someone (let's be candid, probably me) got confused by the fact that `nt` elements have a `def` attribute and thought they were definitions. They're not. I've changed things so that the `prod` elements are now stored in the database. There's only going to ever be one of those.
I had to tidy up a few things to make that work, and we can't abandon support for `nt` files in 'etc' documents because we have existing files that don't get regenerated.
I also cleaned up the cross-reference error to …
=> Fix problem rendering xnt elements

specifications/xpath-functions-40/src/function-catalog.xml
The changes made to redefine array functions in terms of `array:members` and `array:of` rather than `op:A2S` and `op:S2A` weren't applied to array:get because that was the subject of a separate PR to add the `fallback` option. This PR corrects the omission.
=> Fix residual reference to op:A2S which is no longer defined

specifications/xpath-functions-40/src/function-catalog.xml
Fix #398 
Fix #390 
This PR attempts to address the questions raised in issues 389 and 390:
1. It adds a `unc-path` option that is used to guide the parsing and construction of URIs that represent Windows UNC paths
2. It adds a `filepath` property to the result of `parse-uri`. This property represents the local path part of the URI. For file: URIs, this is the local path.
3. It addresses the use of "`|`" in URIs to represent the ":" in Windows filenames
4. It clarifies that percent-decoding a path also involves intepreting the result as a UTF-8 sequence
5. It clarifies that percend-decoding and encoding apply to the query parts of a URI as well.
=> Revise parse/build URI functions for UNC names

specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml
This PR fixes editorial issues in the XSLT 4.0 spec: issue #373, issue #384, issue #423. It also updates the XSD schema for XSLT 4.0 to incorporate most of the syntax changes that have been made to date (though further checking is needed), and updates some 3.0/3.1 references to 4.0 references.
=> Editorial updates to XSLT spec

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Fix #438 
Clarify that the control characters #x1 through X1f and #x7f through #x9f must be output as character references except for the whitespace characters #x9, #xA, #xD, and #85.
=> Attempt to clearify XML serialization of control characters

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/back-matter.xml
Addresses issue #241 by providing functions to parse and format integers in any number base from 2 to 36.
=> Functions to parse and format hex integers

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Following actions from review on 25 Apri 2023 (QT4CG-032-02), revises the new syntax of numeric literals to disallow trailing underscores. Also adds more notes and examples.
=> Revises numeric literal syntax

specifications/css/qtspecs.css, specifications/xpath-functions-40/src/function-catalog.xml, style/xmlspec-2016.xsl
This PR addresses points raised in the comments on #465.
If an `fos:expression` element is a code block, nest an `eg` inside it:
```xml
<fos:expression><eg><![CDATA[let $input := 3936256
return fn:iterate-while(
$input,
function($result) { abs($result * $result - $input) >= 0.0000000001 },
function($guess) { ($guess + $input div $guess) div 2 }
)]]></eg></fos:expression>
```
I found four examples where an `fos:expression` contained more than one newline and I added `eg` wrappers in those cases. 
There are many more `fos:expression` elements that contain a single newline, but automatically formatting them as code blocks was often unsuccessful. Many of those cases seem to be just newlines entered for authoring convenience.
I also fixed the CSS for code blocks and attempte to remove trailing …
=> Per comments on #465, improve presentation of multi-line expressions

specifications/xpath-functions-40/src/function-catalog.xml
Per [Issue 321](https://github.com/qt4cg/qtspecs/issues/321), I've added a new note and two additional simple examples noting the adaptive serialization method to draw attention to this feature in the existing specs.
=> 321: Add new note and examples demonstrating adaptive serialization method

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
#471: I’ve removed the `fn:` prefixes from the function calls in the examples.
I have left pretty much all `true`/`false` strings untouched, since I’m not sure what would be the most consistent approach to clean them up. It will be better anyway to create a separate PR for that.
=> 471: fn: prefix removed from function calls in the examples

style/xsl-query-2016.xsl
This is a small stylesheet change which has the effect that the glossary in the XQuery specification (and elsewhere) now uses natural language sort order, so upper-case terms like `Gregorian` and `NaN` now appear in their proper alphabetic sequence.
=> Use natural language sort order for glossary

specifications/xpath-datamodel-40/src/attribute.xml, specifications/xpath-datamodel-40/src/xpath-datamodel.xml, style/xmlspec-2016.xsl
Close #500 
On closer inspection, there were only a few places where typographic quotes *were not* used in prose. I've fixed those. I think the DM spec could probably use an editorial pass to add `code` around some literals, but I'm not doing that in this PR.
I've left typographic quotes around code and literals because I don't think straight quotes would be an improvement: the literal `“<code>3</code>”` doesn't need straight quotes because the quotes are not part of the literal.
=> Fix typographic quotes in XPath Data Model

specifications/xpath-functions-40/src/function-catalog.xml
This PR fixes the examples in the `parse-uri()` function. It also makes a small change to the `filepath` property, eliding it when the scheme is known not to be file.
=> Fix examples, change filepath definition slightly

specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
In 3.1 XQuery processors were allowed to predeclare these prefixes; in 4.0 they are now required to do so.
=> 485: Predeclare the prefixes math, map, array, and err

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml
(1) drops the mathematical operator symbols appendix, which allowed an extensive range of non-ASCII characters as synonyms for language keywords, (2) retains × and ÷ as synonyms for multiplication and division, (3) allows full-width `<` and `>` in operator symbols in place of the usual ASCII characters, to avoid the need for XML escaping.
=> 460: Fix math symbols

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Addresses issue 436 by introducing syntax similar to Java, C#, and JS for anonymous inline functions (lamda expressions). This involves finding a new symbol for the existing "thin arrow" operator; it also gives an opportunity to show how lambda expressions can be used in pipelines.
Some points for WG consideration:
(a) Do we really want the curly braces around the function body to be mandatory?
(b) What symbol should we use for the mapping arrow? I've used `=!>` as it suggests to me the combination of function application and sequence mapping.
(c) Should we reinstate the special syntax for arity-one "focus functions" (`->{@salary})` ) which is dropped in this proposal
(d) I haven't necessarily worked through all the changes to examples needed, e.g.. in the XSLT and F+O specs.
=> 435, 53, 436: lambda expressions, thin arrows

specifications/xslt-40/src/xslt.xml
Makes a further correction to an example identified in issue #418, and adds to the example giving an alternative solution
=> 418: Correct and expand an XSLT example

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Reworked this PR to deal with merge conflicts. Technical change was already accepted. Made a correction to the "equivalent expression" published in the spec, which has now been tested (and was found wanting...)
=> 125: Rename array:partition as fn:partition

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/xpath-backwards-compat.xml, specifications/xslt-40/src/function-catalog.xml, specifications/xslt-40/src/xslt.xml
`NaN`, `INF`, `-INF` and `+INF` was easy, boolean values were trickier:
* I used `<code>` for “The result/value/option/property is true/false”, “is set to true/false” and similar.
* I didn’t tag “This is true/false”, “The condition is true/false”  and similar.
I hope there won’t be too many conflicts if this is directly merged after #509.
=> 471 (3): Render false/true/NaN/INF/-INF/+INF as code

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-examples.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/xslt.xml
I’ve removed additional `fn:` prefixes from examples and `eg` code blocks. I have kept prefixes in the rules and formal code snippets untouched.
In the initial comment of #471, I have listed the remaining cleanups for which I want to prepare PRs.
I’ll wait until this and possibly some other PRs have been merged.
=> 471 (2): Remove more fn: prefixes

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml, style/assemble-spec.xsl, style/grammar2spec.xsl
This PR is an extensive revision to the rules for tokenisation that corrects a number of errors: 
- The problem mentioned in issue 237, namely the lack of clarity in the "longest token rule". This PR fixes this by clarifying what this rule means and where it applies. In particular it tackles the issue of "complex terminals" such as element constructor expressions and string templates where a symbol that is a single token at one level (in the sense that whitespace is constrained) also contains enclosed expressions.
- Some productions/tokens were misclassified or omitted from the relevant lists of tokens in the appendix. This has been fixed in part by using general rules in the grammar2spec stylesheet to generate lists of tokens, rather than relying on annotations in the grammar file.
The …
=> 237: Revise tokenisation appendix

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml
This PR reinstates "focus functions", using the syntax `function{EXPR}` rather than `->{EXPR}`. If accepted, this resolves issue #503.
=> 503: reinstate focus functions

specifications/xpath-functions-40/style/merge-function-specs.xsl
This is a purely editorial change to the stylesheet that formats examples in the F&O spec; it changes the presentation to be a two-column table containing expressions and results. The intention is to reduce clutter and to improve the readability where code samples (either expressions or results) need multi-line rendition.
In the vast majority of cases the change is clearly (IMHO) an improvement, but further tweaking is possible:
* There may be scope for tailoring the CSS (for example, I don't like the fact that table cells are centred vertically).
* Some of the tables (e.g. parse-uri examples) take too much horizontal space; the code should be edited to reduce the line length
* Examples are sometimes introduced with a free-standing paragraph tag rather than with fo:preamble, which …
=> Editorial: present F&O examples as tables.

specifications/xquery-40/src/expressions.xml
A trivial markup error that leads to the meta-variable E1 being wrongly rendered.
=> Fix typo in XPath §2.4.5 - E1 should be tagged as code not as var.

specifications/xslt-40/src/xslt.xml
A comment to issue #82 identified this typo.
=> Fixes a simple error in the description of XSLT error XTSE4020

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
My previous attempt to make a pull request for this change got lost somewhere in the process; here is a renewed attempt. The changes are in response to comments made during the review of the orginal deep-equal() proposal, recorded in issue #382
=> 382 simplify rules for whitespace in fn:deep-equal

specifications/xquery-40/src/ebnf.xml
As proposed in issue #536, this change disallows mixing of ordinary and full-width angle brackets in the same token.
=> 536: disallow mixing of symbols in operator tokens

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Resolves issue #513 by removing the requirement for an inline function expression on the RHS of an arrow operator to be enclosed in parentheses.
=> 513: after arrow operator, inline function no longer needs parens

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Require parentheses around the parameter list in a lambda expression, even when there is only one parameter, to avoid the problem of needing whitespace before the arrow. Resolves issue #548.
=> 548: require parens around lambda arguments

specifications/xpath-functions-40/src/function-catalog.xml
This PR provides cross-references in the form of notes between members of the pairs `items-before()` & `items-ending-where()` and `items-after()` & `items-starting-where()`. The goal is a light editorial intervention to enhance function discovery. (Anticipating a user who, at any one of these spec descriptions, wonders how they might exclude/include the first matching item.)
=> Added fn:items-X cross-references

specifications/xpath-functions-40/src/xpath-functions.xml
Mainly updates to the changes appendix. Also improve the status section, and correct the bibref to the EXSLT specs.
=> Editorial: Updates to back matter and status section of F+O spec

specifications/css/qtspecs.css, specifications/css/w3c-base.css, specifications/css/xpath-functions-40.css, specifications/xpath-functions-40/style/merge-function-specs.xsl
Further to #560, I'll just merge this if it passes.
1. Make the `<pre>` font the same size as the other monospaced environments
2. Tighten up the spacing in function signatures
3. Make table-formatted examples use valign=top
4. Add subtle shading to table-formatted examples so the rows are easier to distinguish.
=> More typographic changes

etc/status-entities.dtd, specifications/xpath-datamodel-40/src/xdt-datatypes.xml, specifications/xpath-datamodel-40/src/xpath-datamodel.xml
Minor corrections to XDM chapters 1, 2. 
* `expanded-QName` versus `expanded QName`. The latter outnumbered the former ca. 3:2, and is better, so I with with it.
* some language pointing to tables & lines, language rendered obsolete by @ndw 's nice new graphs, excised
* other minor edits for clarity, consistency
=> Minor editorial corrections, XDM chh. 1, 2

specifications/xslt-40/src/schema-for-xslt40.xsd
This PR applies the errata to the XSLT 3.0 version of the schema, and extends the schema to support new syntax that has been introduced in XSLT 4.0.
Fix #567.
=> 567: schema for xslt40

specifications/css/xpath-functions-40.css, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl
This is a purely style related change. It supports role=wide on fos:example elements. If an example is identified as "wide" then the presentaiton is in sequential rows of the table rather than adjacent columns. See, for example, `parse-uri()`.
=> Support role=wide on fos:examples

.github/workflows/build-specs.yml, .gitignore, build.gradle, specifications/xpath-functions-40/style/generate-qt3-test-set.xsl
This PR should update the build so that the test-suite `app/fo-spec-examples.xml` file is automatically build when the spec is published. The PR test won't tell us anything, so we'll have to merge it and see what happens...
=> Automatically generate app/fo-spec-examples on build

specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml
Following review and acceptance of the proposal introducing the concept of function identity (PR #525, Issue #520) this PR makes some refinements in response to comments raised during the review, especially in the following areas:
* clarification as regards named function references to context-dependent functions
* relationship to (in)determinacy of a function
* avoiding the phrase "new function item"
* stating that the identity of a function item such as fn:count#1 applies even across execution scopes, e.g. calls to fn:transform.
=> Action QT4CG-036-02: Further elaboration of the rules for function identity

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
This PR acts on #464 by revising the description of steps involved in normalizing a sequence that is input to serialization. I normally would wield a light editorial hand, but the issues raised in #464 as well as closer reading of the prose convinced me that a wholesale revision would be beneficial. For example, new sequences were described as if the reader already knew about them, but they are really only introduced as the last sentence in many steps.
I have capitalized on the original version of step 1's appeal to `array:flatten` to abbreviate the description for two of the steps.
=> 464: Revised narrative of normalization steps for serialization

specifications/xpath-functions-40/src/fos.xsd, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Improves the stylesheet that generates the BuiltInKeywords.xml test set, using example values for arguments where appropriate, taking these from the function catalog.
=> Editorial: improve generator for keyword tests

specifications/xpath-functions-40/src/function-catalog.xml
Parameter name aligned with other functions (`fn:format-dateTime`, `fn:lang`, others).
Closes #317.
=> 317: fn:format-integer: $lang → $language

specifications/xpath-functions-40/src/function-catalog.xml
Corrects the syntax of the lambda functions in these two examples. Also improves the formatting.
=> Editorial: Correction to map:filter examples

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
This PR is purely editorial. It addresses the problems described in issue #585, in particular, the syntax of dynamic function calls is now described before the semantics.
=> 585: [Editorial] Rearrange text (and grammar) for dynamic function calls

specifications/xslt-40/src/xslt.xml
=> 592: (XSLT, Editorial) Add missing description of exponent-separator

specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml
The main issue turned out to be spurious; there is in fact an explanation of the order attribute in the right place. But I made a couple of other minor editorial changes, including dropping the default for @data-type in the (non-normative) schema for XSLT 4.0 - the default of `data-type="text"` is inappropriate because it forces conversion, e.g. of dates to strings, and the default should be no conversion.
Fix #588.
=> 588: (Editorial, XSLT) minor clarifications regarding xsl:sort

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
I decided to create a PR for the initial proposal of this function, as I came across at least two other use cases for it since the issue was created.
I believe that the `group by` clause is the best choice for more complex operations, such as advanced comparisons or creating histograms.
=> 123: fn:duplicate-values

specifications/grammar-40/xpath-grammar.xml
=> [Editorial] Drop the unused symbol URILiteral from the XPath grammar appendix

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/style/generate-qt3-test-set.xsl
This PR contains lots of fixes in the XQFO examples and improves the formatting of examples with nested arguments and multiline expressions.
It’s probably helpful to merge it as soon as possible to avoid conflicts with other PRs.
=> XQFO Examples: Fixes, Formatting

specifications/xpath-datamodel-40/src/dm-example.xsd, specifications/xpath-datamodel-40/src/xpath-datamodel.xml
Note, the example was invalid because of a failure to access the included xsd file.
=> XDM minor edits, back material

specifications/xpath-datamodel-40/src/attribute.xml, specifications/xpath-datamodel-40/src/comment.xml, specifications/xpath-datamodel-40/src/document.xml, specifications/xpath-datamodel-40/src/element.xml, specifications/xpath-datamodel-40/src/namespace.xml, specifications/xpath-datamodel-40/src/processing-instruction.xml, specifications/xpath-datamodel-40/src/text.xml, specifications/xpath-datamodel-40/src/xpath-datamodel.xml
Per #616 names of nodes have been set lowercase. This PR does not address the good suggestion that xrefs and styling be selectively applied. That is reserved for a future pass.
=> [616] Converted X Node to x node

specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/introduction.xml, specifications/xquery-40/src/xquery-header.xml
All minor edits. Some edits are motivated by an attempt to address broken parallelism or some other form of localized inconsistency. Does not include questions about function descriptions, raised at #624.
=> XPath minor edits, chh. 1-2

specifications/css/xpath-datamodel-40.css, specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-datamodel-40/style/data-model.xsl
As noted in Slack, chapter 4 of the XDM specs is out of place. In this PR I have moved the very general material in chapter 4 to the preamble of chapter 6 (now 5), which provided the opportunity to orient the reader to the structure of that chapter.
Cross-references to chapter 4 have been search for and dealt with. The CSS deletion comes from my observation that there is no such class `infoset-mapping` in the resultant HTML file; section 4's `infoset-mapping` is an id.
=> Removed chapter 4 from XDM

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/schema-for-csv.xsd, specifications/xpath-functions-40/src/xpath-functions.xml
This is a spec proposal for `fn:parse-csv()` from #413.
I've tried to cover off most of what was discussed in that issue, but I have avoided dealing with backlash escapes (per @ChristianGruen's early comment), sticking with the RFC 4180 quoting approach.
There are some issues with the structure where I tried to follow the existing structure of chapter 15, but that leaves the function definition in 15.4 separated by a lot of text before the wider format discussion in 15.7. The split between function def and context affects the JSON and HTML parsing functions too, so I have avoided trying to fix that as well in this PR.
If this meets with approval, I'll squash commits and rebase before merging.
=> 413: Spec for CSV parsing with fn:parse-csv()

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #414 
This PR addresses ACTION QT4CG-036-01 on me.
=> 414: Attempt to implement expanding the allowed character repertoire

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xslt-40/src/xslt.xml
1. `map:of` renamed to `map:of-pairs` (as a hint that the input must match a specific format)
2. `array:of` renamed to `array:of-members` (as a hint…)
3. add `map:pair` for creating a single pair
4. add `array:split` for decomposing arrays to singleton arrays
=> 508: New Map & Array Functions: Inconsistencies

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xquery-40/src/expressions.xml
Minor edits to ch. 3 of XPath spec. Note, this PR includes an adjustment to the XDM spec, in the form of a cross-reference, because the terms "string value" and "typed value" are heavily used in XDM but defined only in XPath.
=> XPath spec ch. 3 minor edits

specifications/css/showdiff.css
See comments #636 . The following targets all additions, deletions, changes, and off, regardless of what HTML element (as written didn't catch <li>, and who knows what other constructs might be in the wings). Checked in the browser developer tools to make sure the new rules wouldn't be overshadowed.
=> Adjusted CSS to target classes, not element + classes

specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Add covers-40 attribute to the generated test set for function keywords, to avoid failures in app-CatalogCheck test Catalog014
=> Add covers-40 attribute to generated tests

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Uses a record type (record(key, value)) for the return type of map:pair, to give more precision and to align with map:pairs() and map:of-pairs()
=> Better return type for map pair

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Old `->` lambda syntax removed from various examples; minor unifications.
I believe it’s ready to merge; please jump in otherwise.
=> 561: Editorial (abbreviation fn=function, drop lambda syntax)

specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml
Various small edits. I added two simple examples to help readers quickly understand the difference between `=>` and `=!>` before going to more complex examples.
=> XPath minor edits, 4.16 through end

specifications/xpath-functions-40/src/xpath-functions.xml
Added note clarifying the relationship between context and focus, for the purpose of illustrating the relationships between focus/context in/dependent functions. Wrapped with companion `<note>`s in a parent `<notes>`.
=> XQFO context/focus in/dependent functions clarification note

specifications/xpath-functions-40/style/merge-function-specs.xsl, specifications/xpath-functions-40/style/xpath-functions.xsl, style/xmlspec-2016.xsl
1. Put the XSLT processor version comment at the end of the file instead of the beginning. Putting it before the `<!DOCTYPE html>` forces browsers into quirks mode.
2. Improve the XPath Functions stylesheets so that they don't put `div` elements inside `p` elements when outputting examples.
=> Style fixes

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
I did my best to define rules for a counterpart of the `fn:encode-for-uri` function, including various edge cases.
I’m convinced that the function has been requested often enough to justify its inclusion in the spec. I’m also aware that users may have different expectations regarding the details of the conversion rules. On the other hand, this discussion can be observed for other languages as well, and that’s mostly due to the… heterogeneous history of URIs, not the actual implementations. For example, `URLDecode.decode` in Java converts the plus character to a space, and JavaScript’s `decodeURI` adopts it unchanged. I decided to convert it as well, as `fn:encode-for-uri` encodes the plus sign to `%2B`.
@ndw My rules have largely been inspired by your decoding rules for `fn:parse-uri`. I …
=> 600: fn:decode-from-uri

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
=> 637: allow true() and false() as function annotation values

specifications/xpath-functions-40/src/xpath-functions.xml
Most substantive change is the trimming of prose held over from before the revision of the diagrams.
=> XFO minor edits, chap. 1

specifications/xpath-functions-40/src/xpath-functions.xml
This PR applies my action items for updating the HTML XDM mapping around namespaces and local names.
Note: this currently makes `dm:namespace-nodes` return an empty sequence. I'm not currently sure what the best approach is here.
=> HTML namespace changes

specifications/xpath-functions-40/src/xpath-functions.xml
Clarifies the rules for constructor functions, especially for list and union types, and for types defined by means of type aliases rather than in an imported schema. Fix #687.
=> 687 Clarify constructor functions for user-defined types

specifications/xpath-functions-40/src/function-catalog.xml
Completes action QT4CG-042-02.
1. Rework the query segments so that they're a simple map of key/value pairs.
2. Rename `query-segments` to `query-parameters`.
=> 566: Rework query parameters on build-uri/parse-uri

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml
=> 701: fn:concat: Support for 0 or more arguments

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
Fix #129 This replaces the previous attempt from several months ago, which had too many conflicts to be salvageable.
This is a wide-ranging and pervasive change, and I would like the changes to be applied promptly and incrementally to reduce the risk of conflicts, even if further work is needed later. This first PR addresses the XQuery and XPath language specifications. Further changes (in subsequent PRs) are needed for F+O and for XSLT. There are also a couple of minor changes affecting Serialization (but none affecting the data model).
=> 129 (1): XPath and XQuery changes for introduction of context value

specifications/xslt-40/src/xslt.xml
Rework PR 664 (fix for 663) on new baseline
Fix #663.
=> 663: Describe how calls to xsl:original with keywords work

specifications/xpath-functions-40/src/function-catalog.xml
Add a note to clarify the behaviour of load-xquery-module.
Fix #725
=> 725 Add clarification note for load-xquery-module

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
Implements the CG decision to roll back the changes that introduced two separate default namespaces for elements and types.
Fix #372
=> 372 Rollback the default namespace changes

specifications/xslt-40/src/xslt.xml
Ensures that an xsl:fallback instruction is not processed in forwards compatibility mode, so that errors in the instruction are reported rather than being silently ignored; informally encourages adoption of the same rule in 3.0 and earlier processors where possible.
Fix #649
=> 649: fix an xsl:fallback problem

specifications/xpath-functions-40/src/function-catalog.xml
Editorial: Some XQuery equivalents were buggy, and the formatting was unified.
=> XQFO Examples: minor fixes, formatting

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml
Fulfils action QT4CG-047-01 : the CG decided to rename break-when as split-when. Also applies a few minor editorial corrections in the same general area.
=> QT4CG-047-01: Rename break-when to split-when, plus minor editorial cleanup

specifications/xslt-40/src/xslt.xml
=> QT4CG-048-01: xsl:mode/@as with built-in templates

specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/conformance.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
Fix #647 
Note: Need to check that this builds successfully. In my working copy, the new text for "import schema" found its way into the "xquery-assembled.xml" file but not into the final HTML. I can't see any reason for this.
=> 647: schema location hints

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml
Allows for expressions interoperable between XPath and XQuery. Fix #653.
=> 653: Add string literals E".." and L".." to control entity expansion

schema/xsl-query.dtd, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/conformance.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/introduction.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xquery-40/src/xquery-header.xml
Includes the following changes:
* Clarification of the syntax and semantics of the version number in the XQuery version declaration
* Updates to front and back matter to reflect the current status of the 4.0 specs
* Update cross-spec references to point to the 4.0 specs rather than 3.1 specs
* A DTD change from spec="SER40" to spec="SE40" to reflect the name of the /etc file generated by the gradle script.
Fix #765
=> 765 Update version references etc to 4.0 status

specifications/xslt-xquery-serialization-40/src/bibl.xml, specifications/xslt-xquery-serialization-40/src/errors.xml, specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
1. Errors are raised, not signaled
2. Cross-references point to 4.0 specs rather than 3.0/3.1
3. Some internal markup changes for tidiness
Partial fix for #783 as it affects the serialization spec.
=> 783(part) - Editorial changes to Serialization spec

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Light edits for consistency.
- Examples in `char()` have been reordered so that the most interesting and useful examples are at top.
- Substring functions were difficult to read in the specs because of the overly long collation URI. These are now bound to a variable, to enhance legibility.
- Schema location fixed.
- extra examples in `string-length()`, to help users recognize the role of combining characters.
=> XQFO edits 5.4-5.6

specifications/xpath-functions-40/src/function-catalog.xml
I’ve eventually renamed `$pairs` to `$input` (I didn’t rename `$input` to $members` as initially suggested, as we have `$member` parameters in other functions that are of type `item()*`, not `record(value as item()*)`).
Closes #469
=> 469: array:of-members, map:of-pairs: Signatures, Examples

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
Fix issue #65. Basically, fix the bug whereby `xmlns="xxx"` changes the default namespace for element NameTests, while retaining bug-compatibility.
=> 65: Allow xmlns="xxx" to NOT change the default namespace for NameTests

specifications/xpath-functions-40/style/merge-function-specs.xsl
Stylesheet changes to improve the formatting of F&O examples. (But they still aren't perfect...!)
1. Variables used by the examples are pulled out under a separate heading.
2. If any examples include long lines, then single-column ("wide") format is used automatically.
3. In two-column layout, if the left-hand column uses "eg" format, then so does the right-hand column. (But it would be nice to get rid of the grey background for this case).
=> Improve formatting of FO examples

specifications/css/xpath-functions-40.css, specifications/xpath-functions-40/style/merge-function-specs.xsl, specifications/xpath-functions-40/style/xpath-functions.xsl
Obviously, I should have done icons for functions that have changed as well. So now I have. I'm not convinced that the 🆙 emoji is sufficiently different from the 🆕 emoji. Maybe I should try to make them different colors or something. But it's a start.
=> Highlight changed functions in the ToCs and headings

specifications/xslt-40/src/xslt.xml, specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Proposes XSLT 4.0 and Serialization 4.0 changes resulting from the generalization of context item to context value in XPath 4.0.
The serialization changes are purely editorial.
In XSLT, we acknowledge the introduction of the context value in XPath but don't take advantage of it; at the XSLT level, the context value for an instruction is still always a single item. The only technical change is that we allow xsl:evaluate to pass any value as the context value to the dynamically evaluated expression (while retaining the name of the relevant attribute "context-item").
Fulfils action QT4CG-046-01
=> 129 XSLT40 and SER40 changes for context item -> value

specifications/xslt-40/src/xslt.xml
See issue #783.
Errors are raised, not signalled or reported or generated or thrown.
=> 783 XSLT: errors are raised

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Attn @ndw -- these edits pertain to 6.6.1 `fn:parse-uri` and require your careful review.
- `hierarchical` option appears in the rules of the function but not its preamble
- "This function is described..." moved to anticipate the actual narrative. 
- I was a bit thrown by the phrase "This approach...is not implementation advice" because "approach" is vague and the reader is left with the impression that a good deal of _something_ that follows is non-normative. We offer non-normative prose in the rules, but that informal prose is normally followed by an equivalent description that _is_ normative. I did not make any edits in this area, but I would recommend clarification as to exactly what parts of the narrative are normative and which are non-normative.
- The period-to-colon change at …
=> Edits to parse-uri()

specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/query-prolog.xml
I’ve chosen XPST0017 over XPST0003 (it felt more intuitive to me).
Closes #660.
=> 660: Static functions, default parameters, XPST0017

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
In addition to a minor typo, note the following:
- rearrangement of a rule for `$input` (the original syntax, mixing types and derived types, confused me)
- examples in `X-from-Y` duration functions to help illustrate the problem when mixing the two components of a duration.
=> Minor edits, XQFO chh. 7, 8

specifications/xpath-functions-40/src/function-catalog.xml
As CG observes in [issue 566](https://github.com/qt4cg/qtspecs/issues/566#issuecomment-1787666119), there are still a couple of small problems with `fn:parse-uri()`.
1. The regular expressions used to parse the fragment identifier and query are incorrect. The URI specification allows `?` to appear in a query string and `#` to appear in a fragment identifier, so the expressions have been rewritten to match everything after the first `?` and `#`, respectively, even if they contain additional `?` or `#` characters.
2. The description of how to interpret the regular expression for parsing a Windows file path preceded by slashes was incorrect. It caused the leading "/" to be lost. That's been corrected.
=> 566 A few minor fixes for parse-uri

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml
Introduces mutual promotion between xs:base64Binary and xs:hexBinary. Fix #130.
Reorganises the material on type promotion. Supersedes PR #538.
=> 130 Binary Promotion

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Pursuant to action QT4CG-051-02, here is a proposal for `fn:invisible-xml`.
There are a number of different design choices that could be made. For example, one could argue that a function of the form `fn:invisible-xml($grammar as xs:anyURI, $input as xs:anyURI)` would be the easiest thing for users in many cases. But not in all cases. You might want versions where either the grammar or the input were strings instead of URIs.
I've attempted to craft the smallest proposal that could get the job done.
=> 238: First draft of an fn:invisible-xml function

specifications/xpath-functions-40/src/function-catalog.xml
Drops the `$min` and `$max` parameters, with the effect that this corresponds much more closely to the general computer-science definition of a transitive closure.
The function now computes the set of nodes delivered by the transitive closure of the supplied `$step` function when applied to a given `$start` node, rather than returning a function item that must then be applied to the chosen $start node. This is hopefully easier for most users to understand, and does not lose any useful functionality.
The `$min` parameter of the old function is effectively forced to its default value of 1, and the $max value to its default of infinity.
Fix #754
Fix #554
This PR addresses the main points of #554 in making the function correspond more closely to the mathematical (or at least the …
=> 554/754 Simplify the new transitive-closure function

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
This PR contains error fixes (typos, examples that contradicted the spec text), some (hopefully) improved language and one breaking change.
The current draft uses the type `map(xs:integer, xs:string)` for the `column-names` option to `fn:csv-to-xdm` and `fn:csv-to-xml`. This PR flips that to `map(xs:string, xs:integer)`. It turns out that the examples were already using this, and it seems to me that having the `names` entry in the `csv-columns-record` record type be the transposed version of the `column-names` option that creates it, rather than be the same thing, is counterproductive.
I can think of some examples (a CSV split into several chunks, with only the first containing the headers) where being able to feed the `names` entry right back into another invocation of `fn:csv-to-xdm` …
=> 413: Spec for CSV-related functions

specifications/xquery-40/src/expressions.xml
Fix issue #730
Note: the issue led to a wide-ranging discussion about possible enhancements to the type system, for example adding types for empty maps and arrays. I have ignored most of this, and have focussed on fixing the issue as raised (arising originally on the test suite), namely the incorrect use of `V?` to define a type that allows either an instance of the sequence type V or or an empty sequence.
=> 730: Clarify (and correct) rules for maps as instances of function types

specifications/xpath-functions-40/src/function-catalog.xml
I have added positional parameters to the following functions:
```
array:filter
array:fold-left
array:fold-right
array:for-each
array:for-each-pair
array:index-where
fn:every
fn:filter
fn:fold-left
fn:fold-right
fn:for-each
fn:for-each-pair
fn:index-where
fn:items-after
fn:items-before
fn:items-ending-where
fn:items-starting-where
fn:iterate-while
fn:partition
fn:some
```
Comments:
* For `fn:every` and `fn:some`, the additional parameter seemed useful to me, as a positional variable has been requested for quantifier expressions in the past.
* I’ve also added positional variables to folds.
* I’ve unified and simplified the formal XPath/XQuery equivalencies in the rule sets.
* I’ve dropped some XSLT equivalencies because I felt that the XQuery representations are more concise (I certainly …
=> 516 Add position argument to HOF callbacks

specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Improves the stylesheet that generates the test set `misc/BuiltInKeywords.xml`; specifically, it's smarter about generating acceptable callback functions that won't trigger an unwanted error.
(The generated test calls each function twice, once with positional arguments and once with keyword arguments, and checks that the two results are deep-equal).
=> Improve stylesheet for generating keyword tests

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
=> 856 Drop reference to obsolete error condition in deep-equal()

specifications/xpath-functions-40/src/function-catalog.xml
I decided to follow my initial suggestion and add `unordered` to `fn:deep-equal` instead of adding a separate function for it. My motivation:
* It’s convenient to be able to use the new option in combination with the other options.
* It will be used more often than many other options we’ve added recently.
* It seemed pretty straightforward to add, both in terms of documentation and implementation.
Closes #479
=> 479: fn:deep-equal: Input order

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #847 
The description of `build-uri` was written with the expectation that if a key was in the map, it's value should be used. I don't really want to replace every occurrence of 
if `x` is present in the map
with
if `x` is present in the map and its value is not the empty sequence
So I've attempted to justify that globally with the following paragraph at the beginning of the description:
> The components are derived from the contents of the $parts map. To simplify the description below, any key whose value is the empty sequence is ignored; this is equivalent to the key not being present in the map.
I'm not hugely proud of that bit of prose though. Suggestions for improvements most welcome.
=> 847 Allow uri-structure-record keys to have empty sequence values

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Closes #844. The `items` keyword in the function names (excluding `items-at`) has been changed to `subsequence`.
See #878 for the controversial discussion on what to do with `subsequence-(after|before|starting-where|ending-where)`.
=> 844 New sequence functions: names

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Fix #866
The proposal introduces a new fn:numeric-compare function that differs from lt/eq primarily in that decimals are compared retaining their full precision, rather than converting them to doubles which may lose precision. This makes the comparison fully transitive which makes it safe to use in all sorting algorithms.
The new comparison semantics are exploited in max(), min(), and sort(), and indirectly in highest() and lowest(); they are also referenced for comparing numeric values in XSLT `xsl:sort` (and therefore indirectly in `xsl:merge`) and in XQuery `order by`.
An effect of the change is that max() and min() applied to a sequence of integers now return an integer, not a double.
=> 866 Introduce and exploit new numeric-compare() function

specifications/xpath-functions-40/src/function-catalog.xml
Closes #900. In addition, the equivalent expression for `array:sort` was fixed.
=> 900 fn:sort, array:sort: Parameter names

specifications/xpath-functions-40/src/function-catalog.xml
=> 895 Parameters with default values: allow empty sequences

specifications/xpath-functions-40/src/function-catalog.xml
Fix #898
Changes non-normative text for the doc() and document-uri() functions to make it clearer that the consequences of the normative rules are not quite as previously stated.
=> 898 - relax the constraints on document-uri

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
I have created new (executable) examples for functions name, local-name, namespace-uri, node-name, count, number.
There are of course many other functions that would benefit from the same treatment.
Fix #913
=> 913-new-examples-for-local-name-etc

specifications/xquery-40/src/expressions.xml
Rearranges the spec for lookup expressions so that unary lookup is now defined in terms of postfix lookup, not the other way around; this simplifies the rules when the context value is not a singleton, or when the key specifier expression is context-dependent.
Fix #860
=> 860 Editorial rearrangement of spec for shallow lookup

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
Fix issue #295 
The main changes are:
* In place of the special self-reference syntax "..", we now allow recursive use of type aliases, allowing types to be mutually recursive
* We generalise the places that recursive references are allowed, for example the record type used by fn:random-number-generator is now legal
* Subtyping rules for recursive record types are now defined (this was previously a gap in the specification). Acknowledgements to a John Snelson blog post for pointing me in the right direction.
=> 295: Boost the capability of recursive record types

specifications/xpath-functions-40/src/xpath-functions.xml
Fix #931 
Adds rules for the precision of durations and operations on durations, analogous to the existing rules for dates/times.
=> 931 Add rules for duration precision

specifications/xpath-functions-40/src/function-catalog.xml
Fix #930
The note is obsolete because adjacent text nodes are now combined after stripping comments and PIs.
=> 930 drop obsolete note about comments and PIs

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Fix #530. 
On half a dozen occasions, `escape-uri-attributes` is used where `escape-solidus` is clearly intended.
=> 530 Fix typo, escape-solidus not escape-uri-attributes

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
This PR reorganizes the subsections of F+O chapter 15 (the XML/HTML/JSON/CSV/IXML chapter). There is no change to content apart from a couple of introductory sentences. I'm planning to do some fine-grained work on the content in due course, but to make that easier to review it seems best to do the top-level reorganisation first. I'm therefore hoping that this PR will go through quickly "on the nod" so I can use it as a baseline for the detail changes.
=> Reorganise F+O chapter 15 [editorial]

specifications/xquery-40/src/expressions.xml
Fix #861
This is a complete rewrite of the spec for deep-lookup, hopefully clarifying some edge cases and fixing bugs, but not intended to introduce any major changes.
=> 861 Rewrite spec of deep lookup operator

specifications/xpath-functions-40/src/function-catalog.xml
* Examples were fixed.
* The equivalent expression for `map:values` was changed to `$map?*`.
=> Minor edits (examples, rules)

specifications/xpath-functions-40/src/function-catalog.xml
Editorial (#951): Reverts the changes made in #901 for 4 context-dependent functions.
=> 951 Parameters with default values: fn:lang, fn:id, fn:idref, fn:element-id

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
My first thought was to name the second function `fn:do-while`, but `fn:do-until` with an inversed predicate seemed more appropriate to me.
Issue: #946
=> 946 fn:iterate-while → fn:while-do, fn:do-until

etc/rfc.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
First draft of hash function, proposed in #779.
Error message left as to-do item; guidance from editors appreciated.
I opted to leave out wrapper/cryptographic functionality, such as salting, and to demonstrate via example how it could be done by a developer on their own. In my opinion what we need here is a simple atomic function that can be incorporated into other molecular functions.
I may tinker with the prose description up to CG discussion, so comments are welcome.
=> 779 hash function

specifications/xpath-functions-40/src/function-catalog.xml
This revises #937 (catalyzed by #779) in light CG discussion that approved the PR.
* Output is now `xs:hexBinary?`
* Second parameter `$algorithm` replaced with an option map. In the specs I avoided `fos:values/fos:value`, because this would disallow for case/space normalization, and it would effectively disallow any implement-defined algorithms not on the list of three algorithms, and trigger the dynamic error described in rule 6 in the [option parameter conventions](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#option-parameter-conventions).
* Options map has only one option. It doesn't make sense to provide an option changing the kind of output.
* I think this is the first example of an options map where the `fos:meaning` has rich text (paragraphs, unordered lists). …
=> 937 revised in light of CG feedback

specifications/xpath-functions-40/src/function-catalog.xml
Addresses the use case in issue #989. (But leave the issue open for now).
Discussion point: should we drop the options `char("#32")` and `char("#x20")` as they now seem redundant?
=> 989 (partial) Allow char() to take integer argument

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
=> 959-partial Add fn:seconds function

specifications/xpath-functions-40/src/function-catalog.xml
Issue: #973.
In addition, I fixed the description for the `fallback` option `fn:parse-json`, as it seemed incomplete to me: 
> The function is called when the JSON input contains a special character (as defined under the escape option) that is valid according to the JSON grammar, whether the special character is represented in the input directly or as an escape sequence.
=> 973 fn:parse-json, fn:json-to-xml: number-parser, fallback

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Fix #963 by providing more detail on the expected error handling for partial function application.
Fix #888 by making XPDY0002 a type error rather than a dynamic error.
=> 888, 963: Error handling for unsatisfied context dependencies

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xquery-40/src/expressions.xml
Issue: #949. The major change is the rule for the `name` property of partial function applications for static function calls.
In addition, I have unified the presentation of the different function item expressions.
Affects test cases like `xqhof40` (which need to be fixed with or without this PR).
=> 949 Partial Function Applications: Allow return of function name

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml
=> 720 Add lookup arrow expressions (method invocations)

specifications/xpath-functions-40/src/function-catalog.xml
Reflected the comments of the CG on the specification of scan-left and scan-right
=> 948 Reflected the comments of the CG on the specification of scan-left and scan-right

specifications/xpath-functions-40/src/function-catalog.xml
Fixes the "equivalent expression" to subsequence-where. 
Fix issue #1001
=> 1001 Fix incorrect operator precedence in subsequence-where

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Adds function `fn:take-while`, replacing/reinstating previously proposed `items-before()` and `subsequence-before()`.
Fix #1002
=> 1002 Add fn:take-while function (replacing subsequence-before)

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Defines an option in parse-json and json-doc to define a representation for JSON null, defaulting to `()` as currently used. Selecting a different value may be useful because it bypasses the problem that the `?` and `??` operators flatten the results, causing `()` to be elided.
Suggests use of the QName `fn:null` as an alternative representation; and changes the JSON serialization method to recognize this QName as a representation of null.
=> 960(partial) Recognize alternative representation of JSON null

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml
Changes the precedence of the `otherwise` operator so that `@price otherwise @cost * 2` now means `@price otherwise (@cost * 2)` rather than `(@price otherwise @cost) * 2`.
Fix #1024
=> 1024 Change precedence of 'otherwise' operator

specifications/xpath-functions-40/src/function-catalog.xml
In response to comments noted in the minutes of meeting 066, and made in writing against PR #1008, add a note justifying the absence of drop-while or skip-while functions.
=> QT4CG-066-xx Add note regarding absence of drop-while / skip-while

specifications/xpath-functions-40/src/xpath-functions.xml
Adds a note explaining why whitespace and comments are not explicit in the regex grammar; see action QT4CG-066-01
=> QT4CG-066-01 Add note that whitespace and comments in regexen are lexical constructs

specifications/xpath-functions-40/src/function-catalog.xml
Allows the use of `fn:void#0` when required.
Fix #1029
=> 1029 Make argument of fn:void optional

specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
=> 485 Predeclared namespaces in XQuery: output

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
The changes here are almost entirely editorial, reordering material, removing duplication and changing some of the language for consistency with the rest of the spec. There is one substantive change - the function `csv-to-simple-rows` is renamed `csv-to-arrays`.
Fix #1016
=> 1016 Editorial cleanup - csv-to-arrays

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
The PR introduces an additional `$format` argument to `fn:format-number`, which allows you to override decimal formats with custom properties.
Next, we may need to clarify if the current specification already allows processors to provide custom decimal formats (https://github.com/qt4cg/qtspecs/issues/340#issuecomment-1968856655). It’s not part of this PR.
=> 340-partial fn:format-number: Specifying decimal format

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Gives a more precise definition of blank rows and empty fields, and generally adds detail on how edge cases should be handled.
Fix #1043.
=> 1043 Clarification of CSV edge cases

specifications/xpath-functions-40/src/function-catalog.xml
See issue #1038, which pointed out compatibility problems with using EBV for callback predicates, as proposed in issue #919.
In specifying `fn:take-while` we anticipated acceptance of the proposal to use EBV for predicate callbacks; now that we have decided not to make that change, this PR brings `take-while` into alignment with other functions using a predicate callback.
=> 1038 take-while predicate no longer uses EBV

specifications/xpath-functions-40/src/function-catalog.xml
Changes the default predicate for `fn:some#1` and `fn:every#1` to be `fn:boolean#1`, which takes the EBV of the items in the input sequence. The previous use of `fn:identity#1` caused some unexpected behaviour.
=> 1047 Default predicate for some#1 and every#1

specifications/xpath-functions-40/src/function-catalog.xml
=> 1037 fn:json-to-xml: 'number-parser' option

build.gradle, schema/xsl-query.dtd
I had a brain cramp when I wrote the `build.gradle` file for this repository. This PR fixes that.
It also adds a `nobreak` attribute to the `code` element. The intent, not yet implemented, is that you can say
```
<code nobreak="true">some long, but not unreasonably long expression</code>
```
and the stylesheet will prevent a line break in the middle of the expression.
=> Build fixes

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/schema-for-csv.xsd, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl
Changes parse-csv to deliver the results in a simpler format:
(a) the result structure is less deeply nested: one record with four entries
(b) the actual data is delivered as a sequence of arrays of strings, closely aligned with the result of `csv-to-arrays`
The rules in the spec have also been rearranged to reflect this, so the rules are now organised according to the values delivered for each of these four fields.
The examples in the spec are changed to reflect the new output format; in addition they have been editorially reorganized so each example is more self-contained, avoiding the need for extensive scrolling to find the values of variables referenced in each example.
Fix issue #1052
=> 1052 Simplify the results of parse-csv

specifications/xpath-functions-40/src/function-catalog.xml
It appears that `escaped-crlf-3` might have been intended. @michaelhkay ?
=> Fix broken idref to escaped-crlf in test generation

specifications/xpath-functions-40/src/function-catalog.xml
Rephrasing as suggested in the issue.
Fix #1036
=> 1036 Rephrase the rules for number-parser with liberal JSON

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Two alternatives in the grammar were both EQNames, distinguished semantically. This ambiguity in the grammar is now fixed (no living XPath expressions are harmed by this change).
Fix #1050
=> 1050 Fix ItemType grammar ambiguity

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/function-catalog.xml, specifications/xslt-40/src/xml-to-json.xsl, specifications/xslt-40/src/xslt.xml
Editorial; closes #1060.
This PR attempts to unify the presentation of XPath and XQuery code. It’s not complete, but it should definitely improve the status quo.
The chosen formatting and indentation rules can certainly be discussed. My major objective was consistency: I selected rules that were used frequently enough in the given documents.
Apart from the presentation stuff, this PR fixes various minor bugs in the rules and examples.
=> 1060 Formatting XPath/XQuery

specifications/xpath-functions-40/src/function-catalog.xml
In the course of reviewing the tests for `fn:parse-uri`, I discovered (or perhaps more correctly, @ChristianGruen discovered) that the rules for matching Windows drive letters are inconsistent. This PR fixes that inconsistency.
=> 566-partial Fix colon issue in URI parsing

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
The purpose of this PR is to bring the current F&O draft specification into a state where it is confirmed as the current status quo accepted by the CG.
The following functions (mainly new, some amended) that have been present in the draft for some while, but with caveats about their status, are confirmed as part of the status quo:
- fn:slice
- fn:format-number
- fn:stack-trace
- map:filter
- map:replace
- array:replace
The following functions are dropped (for the time being):
- fn:json
- map:substitute
The actual PR essentially changes text that alludes to the status of these functions, it does not change the actual specifications.
The current state of qt4tests in relation to these functions is:
fn:slice - OK
fn:format-number - missing tests for recent changes
fn:stack-trace - no tests …
=> Confirm status of provisional functions

specifications/xquery-40/src/back-matter.xml
This PR corrects the status of certain language features that the change appendix in the spec incorrectly describes as having not been accepted by the WG., The features in question are:
> The rules for reporting type errors during static analysis have been changed
>     so that a processor has more freedom to report errors in respect of constructs that
>     are evidently wrong, such as `@price/@value`, even though dynamic evaluation
>     is defined to return an empty sequence rather than an error.
This change has in fact been discussed and accepted by the group.  See PRs #603 and #884.
>     Record types are added as a new kind of ItemType, constraining
>       the value space of maps.
Record types have become a fundamental feature of much of our work, with many additional capabilities …
=> Correct the status of new language features

specifications/xpath-functions-40/src/xpath-functions.xml
=> 1019 XQFO: Unknown option parameters

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Makes the keyword "map" in map constructors optional.
Fix #1070
=> 1070 Bare Brace map constructor syntax

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Fix the syntax ambiguity identified in issue #859 by dropping the troublesome construct.
It is hoped something else will be introduced in its place.
Fix #859
=> 859 lookup syntax problems

specifications/xquery-40/src/expressions.xml
Fix #1039
Rather than adding a new feature to the language, we add notes to "order by" and "group by" explaining how the requirement can be met using the fn:collation-key() function.
=> 1039 Add notes referring to fn:collation-key

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
Someone preparing a QT4 status talk for a conference observed that my affiliation on the data model spec was out-of-date.
I'm just going to merge this one without any fanfare.
=> Fix Norm's affiliation

specifications/xquery-40/src/expressions.xml
Adds further notes an examples explaining the consequences of function coercion, especially when applied to maps and arrays. The new notes make it clear that test case MapTest-058 is incorrect; a map, once coerced to a function, cannot be used as a map.
=> 1020 Further notes on the consequences of function coercion

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Issue: #1110.
* [fn:hash](https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-hash): I added `FOHA0001` as error code.
* [fn:op](https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-op): I used `XPTY0004` as error code, as the allowed operators could also be defined as string enumeration.
* [XQuery, Map Test](https://qt4cg.org/specifications/xquery-40/xquery-40-diff.html#id-map-test): Not included in this PR.
=> 1110-partial New error codes

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Fix #122.
Allows the new item type syntax `(A | B)`, replacing `union(A, B)`; the alternatives are no longer restricted to be atomic types. The choice item type is a generalized atomic type if and only if all the alternatives are generalized atomic types.
Note that #122 also proposed unions of sequence types. While that is also viable, I found that unions of item types handled pretty well all practical use cases, and it seems excessive to offer both. Unions of item types proved (a) more useful (b) easier to combine with the existing feature of local union types, and (c) easier to handle in the coercion rules. Providing both is also tricky to handle in the grammar.
=> 122 Choice item types (generalizing local union types)

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml
Fix #796
Fix #231 
Extends "for" and "let" expressions in XPath to allow a larger subset of XQuery FLWOR expression syntax. Specifically:
- Allow positional variables (`at $pos`)
- Allow type declarations (`as type`)
- Allow let/for clauses to be mixed without an intervening `return`.
=> 796,231 - Extend XPath for and let expressions

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
close #1138 
Note, the proposal could do with further editorial work to use standard `options` markup to define the options available.
=> 1138 Merge format and format-name params of format-number

specifications/xpath-functions-40/src/function-catalog.xml
Allows the use of an items-equal callback even when comparisons are unordered, despite the fact that this may have atrocious performance.
close #1142
=> 1142 Drop restriction disallowing items-equal with unordered

specifications/xquery-40/src/expressions.xml
Responding to an action from the review of PR #1132, this editorial PR attempts to improve the definitions and usage of terms such as "schema type", "atomic type", "pure union type", "generalized atomic type".
=> QT4CG-072-01 Clarify schema type terminology

specifications/xpath-functions-40/src/function-catalog.xml
Close #1140 
Having created the issue, per my outstanding action, I thought I'd take a quick look to see how extensive the change would be. AFAICT (though I confess to not looking exceedingly carefully), only two functions are effected. Here, for your consideration, is a PR that resolves the issue.
=> 1140 Replace 'search' with 'target' for indexing functions

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Fix #1094
Lookup expressions (both deep and shallow) are enhanced in two ways:
(a) the syntax is extended to provide options that avoid flattening the result. For example `$V?pairs::K` delivers the result as a sequence of key-value pairs.
(b) a new KeySpecifier format is provided to filter the results by type. For example `$V??type(record(first, last))` selects all items in the recursive content that are of type `record(first, last)`. This replaces the previous syntax `$V??*::record(first, last)` which caused ambiguities with occurrence indicators.
=> 1094 Enhanced lookup expressions

specifications/xpath-functions-40/src/xpath-functions.xml
An error is raised for an option key unless (a) it is listed in the specification, or (b) it is recognized by the implementation, or (c) it is a QName with a non-absent namespace.
Also clarified the rule about accepting an array in place of a sequence (I'm not sure whether this is something that we actually do, and certainly it doesn't happen unless the parameter explicitly allows an array.)
Fix #1166
=> 1166 Clarify rule on invalid option keys

specifications/xpath-functions-40/src/function-catalog.xml
=> 1086 Editorial changes to array:values

specifications/xpath-functions-40/src/function-catalog.xml
Issue: 1170
* Editorial, 2 characters added
* “2. Redundant parens in function signatures“ is obsolete (https://github.com/qt4cg/qtspecs/pull/1182/files#diff-7625c07ae8131ff65c3caa677b188ed2b9b66237312d11c05a2fa2838c6f5c67R21233)
=> 1170 Editorial: fn:index-where

build.gradle
This should be harmless and I would have thought unnecessary, but there were reports of trouble reading Saxon EE 12.2 from Maven. This PR just updates the maven EE repo URI. The old URI redirects to the new one, but maybe that's causing a problem somehow?
=> Update the Saxonica EE repo

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xslt-40/src/xslt.xml
Add distinct-document-order function.
(Somehow this PR also includes changes to XSLT examples consequent on allowing "fn" as a synonym for "function")
=> 1189 distinct document order

specifications/xpath-functions-40/src/function-catalog.xml
I wonder which font I need to use in order to see U+1F476 U+200D U+1F6D1 as a single grapheme. When I naively put the character sequence into an HTML page, the two glyphs will be rendered individually. How can we make sure that the grapheme will be rendered as intended for most people when they read the spec?
=> 73 copy&paste typo in fn:graphemes (combining diaeresis should be ZWJ)

specifications/xpath-functions-40/src/function-catalog.xml
Reverts the change to unparsed-text and unparsed-text-lines so they no longer normalise line endings by default.
Instead an options parameter is added to select this as a non-default behaviour.
At the same time, we add an option to control whether the function is deterministic (that is, returns the same content if called repeatedly with the same URI). In 3.1 the spec stated that implementations might provide an option to do this, but did not provide an interoperable way of setting this option. For compatibility, the default is still to be deterministic.
Fix #1116
=> 1116 Add options param to unparsed-text

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Brings function tests into line with inline function syntax
=> 1192 Allow fn as abbreviation for function

specifications/xpath-functions-40/src/function-catalog.xml
Fix #934 String comparisons in fn:deep-equal
Fix #1167 Merge $collation and $options params of fn:deep-equal
=> 1167, 934 deep equal merge collations param

specifications/xquery-40/src/expressions.xml
Fix #1207
Also a minor change: `$V[23, "fred"]` now throws FORG0006 rather than XPTY0004. This keeps it compatible with 3.1 (in case anyone is catching the errors), and is more uniform: it seems unreasonable for `$V[23, "fred"]` and `$V["fred", 23]` to throw different errors.
=> 1207 Allow numeric predicates when filtering arrays

specifications/xquery-40/src/expressions.xml
Added examples of coercion rules in action, as requested.
Note to reviewers: the XPath spec contains addition paragraphs explaining the effect of the 1.0 compatibility rules.
=> QT4CG-076-01 Add examples of coercions

specifications/css/xpath-functions-40.css, specifications/xpath-functions-40/src/fos.xsd, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl, specifications/xpath-functions-40/style/xpath-functions.xsl
I think this PR completes the work I started before and that we reviewed briefly some time ago.
Note: because this PR involves changes to the schemas and the stylesheets, the PR build is going to be...funky. I don't know if the diffs will be useful either. There are no (intentional) technical changes in this PR. You can preview the built result by look at https://qt4cgtest.nwalsh.com/branch/action-qt4cg-70-01/xpath-functions-40/Overview.html
A few notes:
1. Instead of just reusing `fos:options`, I added `fos:record-description` with a very similar content model.
2. I couldn't completely remove some of the `<fos:type>` elements defined in the globals section at the top of the `function-catalog.xml` because it causes IDREF failures when that file is parsed.
3. I tinkered a bit with the …
=> Rework record descriptions per ACTION QT4CG-070-01

specifications/xpath-functions-40/src/function-catalog.xml
@dnovatchev For your review. The current version of `fn:chain` in the specs has unnecessary verbiage, is out of sync with other comparable spec entries, and has passages that cry out for clarity and concision. I do not think I have made any edits that change any substantive points. A summary:
* Summary simplified
* Rules: prose for the recursive process brought into conformity with other functions in the specs that describe recursive processes.
* Error conditions: two entries, and clarification of the conditions when they are triggered.
* Former note 1 deleted (excessively wordy, introduces unfamiliar or unnecessary terms/concepts).
* Former notes 3 and 4 moved to rules, distilled into more concise prose.
* Former note 5 (now 2) recast to convey what I think was your original intent, and …
=> 517 Major edits to fn:chain, clarification only

specifications/xslt-40/src/xslt.xml
Allow xsl:break and xsl:next-iteration within branch of xsl:switch
Fix #920
=> 920 Allow xsl:break and xsl:next-iteration within branch of xsl:switch

specifications/xslt-40/src/xslt.xml
Adds a sentence saying that when an accumulator rule with capture="yes" matches a non-element node, the capture attribute has no effect.
Fix #1013
=> 1013 [XSLT] Clarify effect of accumulator capture on non-element nodes

specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/xslt.xml
Allows the default namespace for elements and types to have the special value "##any", which causes unprefixed QNames to match elements in any namespace. Use cases include:
- Casual ad-hoc XPath queries, where over-retrieval isn't a problem
- Use with HTML, where it can be unpredictable whether elements will be in a namespace, and where users are accustomed to browser behaviour with its "wilful violation" of the XPath 1.0 specification
- Any environment where multiple namespaces are in use for variants of what is essentially the same vocabulary of element names (for example, where the XML designer has made the mistake of versioning the namespace URI)
=> 296 Allow default-namespace=##any

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml
Implements ForClause / ForExpression iterating over entries in maps.
Note that the feature is described differently in XP and XQ - I have made some starter attempts to reconverge the two specs, but there is more to be done. (However, the change involved reordering sections, which will adversely affect the diff version).
=> 31 Introduce "for key $k value $v in $map"

specifications/xpath-functions-40/src/function-catalog.xml
Changes the function signature of parse-xml and parse-xml-fragment so the $options argument can be set to an empty sequence.
=> QT4CG-081-03 parse-xml-[fragment]: $options should be optional

specifications/xpath-functions-40/src/function-catalog.xml
Fix #1245
Note: since any of the last three arguments can now be present but set to (), the relevant context dependency becomes independent of arity, so the rules can be simplified.
=> 1245 Correct properties of format-DT function family

specifications/xpath-functions-40/src/function-catalog.xml
Fixed a minor typo in one of the examples for fn:scan-right
=> Fixed typo in the example of scan-right

specifications/xpath-functions-40/src/function-catalog.xml
1. Resolve `QT4CG-080-04`: NW to revise p:invisible-xml, fix #991 
2. Resolve `QT4CG-081-04`: NW to update the function signature of fn:invisible-xml
3. Resolve `QT4CG-081-04`: NW to describe why the grammar option can be empty on fn:invisible-xml
=> Revise fn:invisible-xml

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Delete an obsolete note.
Make the spec consistent with regard to the keyword "to-even" vs "half-to-even".
Fix #1291
=> Fix issue 1291 (rounding)

specifications/xpath-functions-40/src/xpath-functions.xml
Added an incompatibility regarding unrecognized option values.
Removed an incompatibility regarding normalisation of line endings in unparsed-text().
Fix #1285
=> Updated list of incompatibilities in F+O

specifications/xpath-functions-40/src/function-catalog.xml
Fix #1096 
Using deep-equal for comparisons seems a reasonable default that avoids the atomization problem.
Note, I would personally be quite happy to drop the function as an alternative resolution.
=> 1096 Redefine array:index-of to use deep-equal for comparisons

specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Stylesheet changes to the stylesheet that generates tests for all parameter keywords in system functions. The changes recognize `fn(` in function signatures indicating that the generated test case needs to supply a function as the argument value.
=> Recognize 'fn' as well as 'function' in signatures

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
New function collation-available()
Existing function fn:collation() no longer fails if the constructed collation URI is unavailable.
=> 1160 Add collation-available() function

specifications/xpath-functions-40/src/function-catalog.xml
What happened was, I discovered I'd messed with the code in two different branches.
In the course of trying to straighten that out, I came to the conclusion that the *real* difficulty in parsing URIs is what to do about all the special cases around `file:`. And that the approach I'd taken in the previous draft was unnecessarily complicated.
I think this is better.
=> 566-partial Rewrite parse-uri

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/fos.xsd, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/generate-equivalence-tests.xsl, specifications/xpath-functions-40/style/merge-function-specs.xsl, specifications/xquery-40/src/expressions.xml
This PR does the following:
1. Makes schema changes for the function catalog to allow an executable specification of a function to be marked up as such.
2. Uses this markup initially for functions in the array namespace.
3. Makes stylesheet changes to render this markup in the published spec.
4. Commits an XSLT stylesheet (not yet integrated into the build system) that runs against the function catalog to produce an XQuery module whose effect is to declare functions based on the "executable specifications" and run the published executable examples against these functions, checking that they produce the expected result. The "success" output of this query (which runs with no source document) is an XML document containing an empty element `<result/>`. (If it has content, this will relate to …
=> 1324 Introduce markup for executable specs

schema/xmlspec.dtd
The DTD defines it as a IDREF type which it clearly isn't.
=> Fix inconsistent definition of return-type-ref-occurs

specifications/xslt-40/src/xslt.xml
Fix #1399.
The only change is to remove a sentence from `<note>...</note>` markup.
=> 1399 clarify fixed-namespaces spec

specifications/xslt-40/src/schema-for-xslt40.xsd
Updates the schema for XSLT 4.0 stylesheets to accommodate changes recently agreed:
* Support for xsl:function/@variadic
* Support for extensions to decimal-format properties, for example `percent="%:pc"`.
=> Update schema for XSLT 4.0 to include agreed syntax changes

specifications/xquery-40/src/expressions.xml
Corrects/clarifies the rules for determining whether A is a subtype of B when either or both is a choice item type.
Fix #1395
=> 1395 Revise rules for subtyping of choice item types

specifications/css/xpath-functions-40.css, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #1401
The main changes are:
- The three derived types xs:integer, xs:dayTimeDuration, and xs:yearMonthDuration are no longer treated as primitive for the purpose of this section. They are now treated as derived types, but given special status where necessary as "quasi-primitive".
- In places where the F+O rules give the same result as the canonical representation in XSD 1.1, we now defer to XSD 1.1 rather than replicating the rules. Many of the rules originate with XPath 2.0, which was published before XSD 1.1, but which anticipated some of the changes in XSD 1.1, for example the use of a seven-component model for dates/times, and a two-component model for durations. XPath 3.0/3.1 failed to take advantage of the resulting opportunity for rationalisation.
- Generally the language is a …
=> 1401 Rewrite of F+O section 20, Casting

specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml, style/leading-tokens.xsl
Fix #1321
Fixed as suggested in the issue. I have added a list of tokens that can appear at the start of a RelativePathExpr, produced by analyzing the grammar using a custom stylesheet leading-tokens.xsl which is available for reuse, but not integrated into the build.
=> 1321 leading lone slash

specifications/xpath-functions-40/src/function-catalog.xml
There's a markup error in the hash function that breaks the automatic test build. This PR fixes that.
(I'm just going to merge this straight away.)
=> Markup fix

specifications/xpath-functions-40/src/function-catalog.xml
This is a slightly more radical alternative to #1388 
In addition to clarifying the encoding rules (maintaining slightly different rules for path segments, query parameters, and fragment identifiers), it removes the `path-separator` and `query-separator` options.
=> 1387b Clarify parse-uri/build-uri encoding rules, and remove options

specifications/xslt-40/src/xslt.xml
Fix #1415
Adds xsl:item-type to the list of declarations.
Adds xsl:array. xsl:map, and xsl:map-entry to the list of instructions.
=> 1415 Add to lists of XSLT declarations and instructions

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
This PR disposes of my action to add `absolute` to the output of `fn:parse-uri`.
The rules that define an absolute URI: "has a scheme", "does not have a fragment identifier", "is a hierarchical scheme" don't fit neatly into a single place, so there are two different places where the setting is considered.
Because of this, I think it's simpler to set `absolute` to `true` when the URI is absolute, but not to `false` when it isn't. That could be rectified with a bit more prose.
=> Dispose of action QT4CG-080-05, add absolute to parse-uri

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
Fix #1391
- Changes the data model to clarify exactly what the annotations of a function item are
- Clarifies the XQuery description of what effect annotations in the query prolog have
- Changes the fn:function-annotations function to return a sequence of key value pairs in which there can be duplicate keys.
=> 1391 Change function-annotations to return a sequence

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/xslt.xml
Fix #1348
Makes some simplifications to the grammar rules, including some of those suggested.
I've avoided removing productions that are referenced by name in the prose of the spec; these names provide a useful handle to relate the syntax to the semantics.
I would love to introduce BNF for a comma-separated list. Invisible XML uses
`XX ** ","`
for zero or more occurrences of XX, separated by ",", and
`XX ++ ","`
for one or more occurrences of XX, separated by ",", and
=> 1348 Some grammar simplifications

specifications/css/qtspecs.css
1. Make the productions a little easier to read by removing the border and background on `code` elements in production tables.
2. Make the background color for production notes a little less ... intense.
=> CSS tweaks for productions

specifications/xpath-functions-40/src/function-catalog.xml
In #1387 @ChristianGruen observes that the `+` seems to be a special case in the `tel:` scheme. In fact, I think we concluded that the special case is that you shouldn't encode the path segment of a non-hierarchical URI.
This PR attempts to implement that.
=> 1387 Another tweak to build-uri

specifications/xquery-40/src/query-prolog.xml
With function declarations, recursive functions can be declared:
```xquery
declare function local:factorial($x) {
if($x > 1) then $x + local:factorial($x - 1) else $x
};
local:factorial(5)
```
We should allow the same for variable declarations:
```xquery
declare variable $factorial := fn($x) {
if($x > 1) then $x + $factorial($x - 1) else $x
};
$factorial(5)
```
I believe it is sufficient to simplify the definition of *initializing expressions* and drop the exception “other than the variable being declared”.
Related: https://www.w3.org/Bugs/Public/show_bug.cgi?id=15791 (the static dependency check was given up before due to `fn:function-lookup`).
Closes #1379
=> 1379 Initializing expression: Allow self references

specifications/xpath-functions-40/src/fos.xsd, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/generate-keyword-test-set.xsl, specifications/xpath-functions-40/style/merge-function-specs.xsl
This PR addresses issue #1461 in a fairly narrow way, without attempting to tackle the deeper problem identified in issue #1336.
This involves expanding the `fos:type` entries for types such as `uri-structure-record` that are referenced in function signatures, resulting in some duplication with the `fos:record-description` entries that describe the same types in a different place.: hopefully the resolution to #1336 will resolve that duplication.
=> 1461 Generate correct tests for functions involving named record types

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Second attempt. Closes #1323 and #1436.
In addition, includes a change to `fn:json-doc($uri)`, and fixed an editorial bug for the `fn:escape-html-uri` function.
=> 1323b Function parameters names: $uri → $source

specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
Attempts an improved (more intuitive) specification for the xsl:array instruction.
Fix #1468
=> 1468 Revise the xsl:array instruction

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #1474
Describes the changes that might be needed to supplied numbers to ensure the output conforms with JSON syntax.
Independently, adds a note to appendix to G.4 to affirm that changes to argument keywords have no backwards compatibility implication, satisfying action  QT4CG-091-01
=> 1474 xml-to-json: ensure numbers are JSON conformant

specifications/xslt-40/src/xslt.xml
* Two largish sections had duplicate prose nearby;
* Some punctuation rendered consistently;
* Some substantive insertions/edits for clarification, when it seemed clear to me.
Let me know if any of these changes are misfires.
=> Modest editorial corrections to XSLT specs through 2.7

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl, specifications/xslt-40/src/xslt.xml, specifications/xslt-40/style/xslt.xsl
1. Changes the pattern syntax to allow any EQName to be used for function calls; the constraints on which functions can be called are defined outside the actual grammar.
2. Reinstate root() as a permitted function
3. Allow `doc()/id()` without requiring parentheses around the second function call
4. Stylesheet changes to point external spec references at the 4.0 specs rather than 3.0.
Fix #1375
=> 1375 bugs in pattern syntax

specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Adds rules for the default priority of new match pattern options such as `element(p:*)` and `element(p|q)`.
Fix #1394
=> 1394 Add new default priority rules

specifications/css/xpath-functions-40.css, specifications/xpath-functions-40/src/xpath-functions.xml, style/xmlspec-2016.xsl
Fix #1357 
This is a purely cosmetic PR. I think @ChristianGruen is right that it is unfortunate that we've lost the distinction between "new" and "only updated" functions. I'm trying to make that work again, in a way that's more visually distinct.
I have:
1. Use `Δ` for changed sections. 
2. Use `Δ➕` for new functions. (I'm making no effort to determine if non-function sections are new or changed; I doubt that it's either worth the effort or likely to be correct. One could argue that `➕` alone is sufficient, but I liked the consistency this way. Even new functions do change between drafts.)
3. Per @michaelhkay, a function is "new" if it doesn't appear on F&O 3.1.
4. I found it distracting that the delta symbol preceded the ToC entry. That's purely aesthetic, I guess, but I've put them at …
=> Update the changed/new marks in the ToC

specifications/xpath-functions-40/src/function-catalog.xml
Fix #1507 
Make the "formal spec" of fn:parse-integer legible (and portable between XPath and XQuery) by avoiding use of XML character references in the code.
=> 1507 Make format-integer spec legible

specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
No issue raised.
Adds links from change metadata in the spec to issue and PR numbers in GitHub in many cases where these were previously missing.
=> Add to changes metadata

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml
1. Adds advice and guidance on avoiding reserved words
2. Drops XQuery-specific material from the XPath spec
3. Adds a paragraph to the incompatibilities appendix
=> Actions QT4CG-095-01 and -02 - follow-up on computed node constructors

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
=> 1519 Add -or-self axes

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
=> 868 fn:intersperse → fn:join, array:join($arrays, $separator)

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Provides four new functions:
- node-kind
- schema-type
- atomic-type-annotation
- node-type-annotation
to return type information using a new record structure schema-record-type.
Fix #148
Partial Fix for #1271
=> 148 New functions to get type information

specifications/xpath-functions-40/src/function-catalog.xml
As noted during the review at yesterday's meeting. (I was supposed to correct it before applying the PR, but pressed the wrong key...)
=> Correct return type for fn:siblings

specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml
Fix #1561 
Test case catalog-005 now passes, showing that all the non-error stylesheets in the test suite are valid against the schema.
=> 1561 Correct the schema for XSLT 4.0

specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Purely editorial; adds cross-references to map:build (for example from XSLT and XQuery grouping) to make the function more visible.
@Fix #1515
=> 1515 Add cross-references to map:build

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/xslt.xml
Fix #1548
XSLT 3.0 specified no default for xsl:output/@indent in the case of the JSON and Adaptive output methods. This PR sets the default to "no".
I believe this is sufficient to close #1548.
=> 1548 Clarify default for xsl:output/@indent

specifications/xquery-40/src/expressions.xml
Merging allowed a `changes` block to become split into two blocks, which isn't allowed.
=> Fix markup error

specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml, specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Fix #1538
I also did some editorial cleanup of the serialization spec, in particular parameters like `indent` now have the value `true` or `false`, while recognizing that some host languages may allow alternative representations such as yes/no or 1/0.
=> 1538 Add XSLT support for json-lines

specifications/xpath-functions-40/src/function-catalog.xml
I have (a) added more explanation of why the conversion is needed, and (b) described the conversions more prescriptively.
Fix #1493
=> 1493 Expand the rules for handling numbers in xml-to-json

specifications/xslt-40/src/function-catalog.xml
I found that the two functions mentioned in the issue (document and function-available) had been updated as suggested. However I also checked all the XSLT-specific functions, and found that for current-merge-group(), the prose has been updated to say what happens if the argument is omitted, but the signature does not actually define a default. I have corrected this.
Fix #69
=> 69 Add default for current-merge-group $source

specifications/xpath-functions-40/src/xpath-functions.xml
The reference to §13.2.9 of the WhatWG DOM spec should be a reference to §13.2.9 of the WhatWG HTML spec.
Fix #767
=> 767 Fix reference to HTML5 spec

specifications/xslt-40/src/schema-for-xslt40.rnc
This PR updates the RELAX NG grammar to be (more) consistent with the XSD grammar (and consequently more correct for XSLT 4.0)
1. Relaxes the definition of QNames so that prefixes declared with `fixed-namespaces` can be supported
2. Adds the `fixed-namespaces` attribute to `xsl:stylesheet`, `xsl:transform`, and `xsl:package`
3. Adds the `xsl:switch` element
4. Adds the `xsl:array` and `xsl:array-member` elements
5. Adds `shallow-copy-all` to the possible values for `on-no-match`
6. Adds `separator` to `xsl:apply-templates`
7. Removes `select` attribute from `xsl:copy`
8. Adds `as` attribute to `xsl:sequence`
9. Updated the declarations for `xsl:accumulator-rule`, `xsl:array`, `xsl:array-member`, `xsl:attribute`, `xsl:catch`, `xsl:comment`, `xsl:map-entry`, `xsl:matching-substring`, …
=> Update RELAX NG grammar for XSLT

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml
As well as allowing `record()` for an empty record type as proposed in #1491, this PR also allows named record declarations in XQuery to have no fields. In the course of implementing this I discovered there was old text in the F&O "Constructors" section which duplicated but had become out of sync with the XQuery spec, so much of this has been deleted and replaced with a cross-reference. Named record definitions for XSLT have not yet been defined, this is unfinished business.
Fix #1491
=> 1491 Empty record types

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Supersedes #529 
Fix #528
Coming back to this after a long gap, I have redrafted the proposal. I've tried to take as many of the comments into account as possible, but I'm aware that I haven't responded to them all.
=> 528bis element to map

specifications/xpath-functions-40/src/fos.xsd, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/style/generate-keyword-test-set.xsl, specifications/xpath-functions-40/style/generate-qt3-test-set.xsl
Fix #1516 
1. Fixes some examples in the spec where the expected results were apparently incorrect
2. Introduces a mechanism for giving a test assertion for an example that is separate from the published result, for example where alternative results are possible
3. Marks some tests as schema-aware so a non-schema-aware processor won't attempt to run them
All the tests for features that are implemented in Saxon now run successfully.
=> 1516(B) Fix problems with testing examples

specifications/xslt-40/src/function-catalog.xml
Fix #1590.
A draft spec for this function is in the function-catalog, but it has never been referenced in the published spec and the draft is incomplete.
This PR has no impact on the published specs, only on processes that access the function catalog.
=> 1590 Drop draft current-mode function from catalog

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Drops the newly-introduced `fn:node-kind()` function in favour of a more general function `fn:type-of()`.
=> 1550 Replace node-kind() with new type-of() function

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl
Changes the rendition of record type definitions so each is now defined in a section of its own, extracted from the function catalog into the narrative spec by means of a processing instruction, following the precedent of function definitions. Record type definitions can therefore be cross-referenced using a specref, but they are automatically cross-referenced if named in a function signature.
Fix #1527
=> 1527 Move record types into separate sections

specifications/xpath-functions-40/src/xpath-functions.xml
Updates and aligns the "Other Operations" sections for maps and arrays.
=> 1602 Editorial update to "other operations" on maps and arrays

specifications/xpath-functions-40/src/function-catalog.xml
=> 1608 add dependency to fn compare

specifications/xslt-40/style/xslt.xsl
I changed `xfunction` refs so that they point to the right URI for 40 functions.
(Partial fix for #1610 )
=> Fix xfunction refs in XSLT

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
I've reworked the rules for selecting a layout. There's probably more to be done, but this is a start - feeback welcome. I'm marking this "revise" for the moment because I haven't finished it yet. There's no deliberate changing of the spec apart from fixing errors.
=> 1592 Rework rules for selecting a layout

specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xslt-40/src/xslt.xml, specifications/xslt-40/style/xslt.xsl, style/xsl-query-2016.xsl
Stylesheet change for cross-spec links (xspecref, xnt, xtermref) to drop the redundant "40" version suffix - for example the suffix becomes DM rather than DM40, since the vast majority of links will point to the 4.0 version of the document.
=> Abbreviate suffixes on cross-spec links

specifications/xquery-40/src/query-prolog.xml
Fix #1628
Hopefully the new rules are clearer. They were motivated by a couple of test cases using weird version numbers such as "4.00".
=> 1628 Clarify rules for XQuery version declaration

specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl
Fix #1554
Changes the heading "formal specification" to "formal equivalent", and expands on the explanatory text.
=> 1554-change-formal-specification-heading

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #1103
Simplifies the spec by doing line-ending normalization unconditionally prior to CSV parsing. CRLF sequences are no longer retained within quoted fields.
=> 1103 Normalize line endings in CSV prior to parsing

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/xslt.xml
Replace `<code>` with `<function>` tags where appropriate.
Fix #1652
=> 1652 Use function markup

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #1627
Minor adjustments to the rules for fn:schema-type, fn:atomic-type-annotation, and fn:node-type-annotation based on implementation and testing experience.
=> 1627 Tweaks to schema type functions

specifications/xslt-40/src/schema-for-xslt40.xsd
We decided to close #374 without further action. This PR just cleans up the relevant schema file by removing the DTD and stylesheet related comment(s).
=> Remove DTD/stylesheet distractions at the top of the schema

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Drop fn:node-kind from the function catalog so it disappears from the function finder
Correct one example of fn:type-of and add some more examples.
Fix #1650
=> 1650 Tidy up fn:type-of

specifications/xpath-functions-40/src/function-catalog.xml
Brings the spec of fn:function-annotations into line with the test cases and examples
Fix #1649
=> 1649 result of function annotations

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
=> 1667 Revise handling of non-XML characters in parse-json

specifications/xpath-functions-40/style/xpath-functions.xsl, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-40/style/diff.xsl, specifications/xslt-40/style/xslt-diff.xsl, specifications/xslt-40/style/xslt.xsl, style/xmlspec-2016.xsl
Addresses part of #1407:
* Improves the section headings and levels for the Types and Subtyping sections
* Level-4 headings (and level-5 if there were any) are no longer omitted from the F&O TOC.
There are other suggestions in #1407 regarding the spec prose that are not (yet) implemented.
Changing the CSS to adjust presentation of level-4 and level-5 headings in the TOC is way above my level of CSS competence, there's some very elaborate logic in this area, and anyone who wants to tackle it is welcome.
=> 1407 TOC structure for types

specifications/xpath-functions-40/style/xpath-functions.xsl
For F&O the automatically-generated appendix of implementation-defined item should link each such item to the nearest containing section that has a `head` child as well as an id attribute.
=> 1688 In "implementation-defined" appendix, fix absent generated link

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Fix #1680 (as suggested in the issue)
=> 1680 Fix switch syntax ambiguity

build.gradle
Changing `xslt.xml` didn't actually cause the HTML for the XSLT specification to be rebuilt. 👎
=> Fix bug in build dependencies

specifications/xpath-functions-40/src/function-catalog.xml
Applies to fn:round, fn:round-half-to-even, fn:divide-decimals
Fix #1705
=> 1705 Say that max precision is implementation-defined

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Issue: #1685
The PR introduces the pipeline operator `->`. If we decide to add it, we could drop `=!>` in a second step and update various examples in the text.
=> 1685 Pipeline Operator

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
=> 1706 Drop "else if" and "else" clauses from braced conditionals

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/schema-for-xslt40.rnc, specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml, specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Reopened pull request introducing ordered maps.
Fix #1651.
=> 1651 ordered maps

specifications/css/qtspecs.css
This PR removes some extraneous space between the rows and columns in the production tables (cellspacing) and turns off the odd grey background on comments. (I don't think the grey backbround was helping any, but if you disagree...)
=> Fix CSS for production tables

specifications/xquery-40/src/expressions.xml, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml
Adds named record types to XSLT, with much the same spec as for XQuery, but some extra tweaks for handling visibility and overriding.
Fix #1485
=> 1485 Add xsl:record-type declaration

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Clarifies the rules for how duplicates are handled by map:merge, map:build, map:of-pairs, and xsl:map.
Introduces a callback option for map:merge that is compatible with map:build and map:of-pairs, to increase commonality between all four functions/instructions.
Fix #1725
=> 1725 Define more detailed rules for duplicates in maps

build.gradle, specifications/css/w3c-base.css, specifications/css/xslt-40.css, specifications/js/toc.js, style/xmlspec-2016.xsl
I'm just going to merge this one because
1. The CG agreed they wanted this
2. All of the changes are presentational, there are no technical changes
3. The PR build won't work anyway
I did make a couple of executive decisions.
The use of "..." as the target to click on didn't seem like a practical affordance. It's not a common use of ellipsis and it looked too much like it simply meant that part of the title was elided. I went with right and down triangles instead. And I added the few lines of JS required to make them "turn".
I added a top-level expand/collapse that does all of the sections. I wasn't happy that with the new UI, there was no way to get an overview of the document by seeing all of the section titles.
I tinkered with the CSS. I'm not uniformly happy with it, especially with …
=> Implement expanding/collapsing ToC

specifications/css/xpath-functions-40.css, specifications/css/xslt-40.css
This is also related to 1747. It "fixes" the problem that @ChristianGruen reported where the function finder obscured content on mobile (narrow) devices. I've changed things so that it isn't at a fixed location on narrow devices. It still appears above the ToC, but it scrolls as normal.
=> Don't fix the function finder on small devices

.github/workflows/build-specs.yml
This PR should build DeltaXML diffs of the EXPath specs...and when merged, should build them on the main build as well.
=> Make DeltaXML diffs on the main build too

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/back-matter.xml, specifications/xquery-40/src/expressions.xml, style/xmlspec-2016.xsl
Fix #1682 
Moves the relevant parts of the operator mapping table into the sections for Arithmetic Expressions and Value Comparisons. Adds links to the op: functions in F&O.
Drops the Type Promotion appendix, moving the rules inline; and drops the term "type promotion"
Adjusts the specs for sum() and avg() so they are now defined directly in terms of pairwise addition of values.
=> 1682 Type promotion and operator mapping

specifications/EXPath/binary/src/binary-functions.xml, specifications/EXPath/binary/src/function-catalog.xml, specifications/xpath-functions-40/src/fos.xsd
Apart from general copy-editing, the main changes are:
* A lot more examples, presented in executable markup format (though they are not yet tested)
* Many functions now have formal equivalents (again, currently untested)
* Allow underscores and spaces in input to bin:hex, bin:octal, and bin:bin
* Use type xs:unsignedByte for octet arguments
* Use an enum() type for the octet-order argument
Fix #1750
=> 1750 Overhaul of EXPath binary spec

specifications/xpath-functions-40/src/function-catalog.xml
=> 1739 drop references to ordering mode in the static context

build.gradle, style/xmlspec-2016.xsl, style/xsl-query-2016.xsl
In order for links to work in the browser, the SVG has to be inline, not loaded from a separate file. For self-document links, I guess this makes sense.
This is a tools-only change.
=> Inline SVG images

specifications/xslt-40/src/xslt.xml
Scraps the increasingly-complicated rules for handling priority of rules with a union pattern.
Fix #1770
=> 1770 Default priority of rules with a union pattern

specifications/EXPath/binary/src/binary-functions.xml, specifications/EXPath/binary/src/function-catalog.xml
Fix #1751
Clarifies BOM handling (and byte order generally) in `bin:encode-string` and `bin:decode-string`.
Also adds a note to `bin:octal` for the prevention of possible misunderstanding.
=> 1751 Clarify BOM handling

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml
Replaces "singleton map" with "single-entry map" and "singleton array" with "single-member array"; the term "singleton" now always means count()=1, not size()=1.
Fix #1789
=> 1789 Fix singleton terminology

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
=> 1716 Generalize syntax of arrow expressions

specifications/xpath-functions-40/src/xpath-functions.xml
Revises the headings for consistency and brevity, to make the ToC easier to navigate at a glance
Fix #1823
=> 1823 Revise top-level headings in F+O spec

specifications/xpath-functions-40/src/function-catalog.xml
Adds an option for deep-equal to treat order of entries in a map as significant.
Fix #1771
=> 1771 Add option for deep-equal to consider map order

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
[ ] QT4CG-111-01: MK to review the editorial comments on PR #1837 and then merge the PR.
Done (along with a couple of other minor corrections noted in passing)
[ ] QT4CG-111-02: MK to fix the typo $in as xs:double+ and 1.3. 1.4 that middle “.” should be a “,”
Already done before the PR was merged
[ ] QT4CG-111-03: MK to add a %method example that uses the arrow syntax.
Done (though the example isn't especially convincing).
Also added another couple of examples and notes in passing.
=> Actions from meeting 111

specifications/xpath-functions-40/src/function-catalog.xml
Fix #1796 
This change does not appear to change any test results. (In other words, none of our tests checked that the return type was explicitly a document node.)
=> Relax the return type of the Invisible XML parsing function

specifications/js/toc.js, style/xmlspec-2016.xsl
Fix #1820 
This PR updates the styling so that a small "Δ" is added to the expand arrow when there are changes or additions in the concealed subsections. It's smaller and not blue. I could argue that this is on purpose so that the marking is different and perhaps more subtle. But the truth is, it was just easier to add the Δ without any markup that would make it larger or blue.
I've opted to conceal the Δ when the ToC is "open" on the grounds that you can see what is or isn't marked new on the revealed subsctions.
=> 1820 Attempt to add change markup in collapsed ToC

specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
Proposal is that in methods, the containing map should be bound to the context item rather than to the special variable $this, so fields of that map are referenced as `?x` rather than `$this?x`.
=> 1845 Revised design of methods to use . rather than $this

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/schema-for-xslt40.rnc, specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml
Actions QT4CG-107-02 and QT4CG-107-03.
The three functions map:build, map:of-pairs, and map:merge now all have the same options parameters, and avoid duplication in the specification. The xsl:map instruction is defined by reference to map:merge.
Although the action suggested specifying these functions to use the first key from a set of duplicates, I found this was not possible because of the way map:put is defined. They therefore use the last key from the set of duplicates.
Fix #1725
=> 1725b Further elaboration of duplicates handling in maps

specifications/xpath-functions-40/src/function-catalog.xml
Fix #1851
Allow ?variety to be absent e.g. for xs:anySimpleType
Define namespace-sensitive by an xtermref to the definition in the XP/XQ spec.
=> 1851 Make ?variety optional; explain namespace-sensitive

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl
=> 1869 duplicate values

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Following up on issue 1341, we decided to drop the position argument from the 4 fold functions.
Most of the changes in this PR are dealing with the collateral damage - changes to "formal equivalents" of other functions that previously relied on fold-left having the position available to the callback function.
=> 1341 Drop position from fold callbacks

specifications/xpath-functions-40/src/function-catalog.xml
Add options to control entity expansion and XInclude processing.
Fix #1857 
Fix #1860
=> 1857, 1860: Add more options to parse-xml

specifications/xpath-functions-40/src/xpath-functions.xml
I cannot imagine how we got a merged PR that included broken markup, but it's probably made a mess of the diffs recently.
=> Fix broken markup

specifications/xquery-40/src/expressions.xml
=> 1862 Coercing to a record type changes map order

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
1. Reinstates the non-capturing group syntax `(?: xxx )`
2. Clarifies that a zero-length matching segment does not overlap an immediately preceding adjacent (but non-zero-length) segment.
=> 1911 Clarifications for regular expressions

specifications/EXPath/binary/src/binary-functions.xml, specifications/EXPath/binary/src/function-catalog.xml, style/xmlspec-2016.xsl
Replaces PR #1909
Adds error conditions for unpacking an integer that is too large for the implementation
=> 1902b bin:unpack out of range error

specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml
Supplies rules for how `fn:function-identity()` should handle maps and arrays.
Also makes the point that labels are ignored. There's a general statement to the effect in XDM that labels are ignored except where otherwise specified, but it's useful to avoid any doubt here.
Fix #1881
=> 1881 Function identity for maps and arrays

specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
=> 451 Multiple schemas in XSLT

specifications/xpath-functions-40/src/function-catalog.xml
Issue #1363 generated a large amount of discussion on how to handle absent keys in map:get() and out-of-range indexes in array:get().
I felt that one of the simplest proposals was to change the $fallback argument to be a simple default value, rather than a function. This eliminates some of the more "clever" use cases, but these can always be achieved in other ways, as the discussion thread demonstrates. Meanwhile reducing `$fallback` to a simple default value makes life easier for the 90% of cases where this is all that is needed (especially for arrays, when the desire is to return a default value rather than throwing an error).
This PR therefore implements that simple proposal.
Fix #1363
=> 1363 fallback becomes a value not a function

specifications/xpath-functions-40/src/function-catalog.xml
Improves the description of the semantics of the `xsd-validation` option on `parse-xml()` and `doc()`. Also brings the two functions into line by adding the `xsi-schema-location` option from `doc()` to `parse-xml()`.
=> QT4-CG-116-02 improve description of validation

specifications/xquery-40/src/expressions.xml
This PR doesn't do what issue https://github.com/qt4cg/qtspecs/issues/1844 suggests, namely dropping the mapping arrow. Instead it picks up a couple of points made in passing in that issue:
(a) drops remaining references to the obsolete =?> operator
(b) simplifies the grammar for arrow expressions
(c) improves the way arrow expressions are described, including their relationship to pipeline expressions.
=> 1844b Arrow Expressions

specifications/css/w3c-base.css, specifications/css/xpath-functions-40.css, specifications/js/toc.js
This is an attempt to complete action QT4CG-116-03.
Part of the confusion in the rendering is that it’s partly done by CSS and partly done by JavaScript and those had gotten out of sync. Given that the JavaScript code has to do some of the work, I changed things so it does all of the work.
I also discovered that the weird Firefox bug where the font size changed was, wait for it, caused by the particular codepoint being used for “changed”. So I, uh, changed it.
We now get ✚ for new sections, ✭ for changed sections, and both when there are both new and changed sections. I spent a bit of time trying to find a third symbol, but gave up.
The markup in the XSLT specification isn’t quite the same as in other specifications, so the results are a tiny bit odd in places. There are some sections …
=> Attempt to improve rendering of the dynamic ToC

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
The PR drops the "uniform" option of `elements-to-maps` into a separate function `elements-to-maps-conversion-plan`, which can be used to analyze a corpus of data and generate a conversion plan for use by `elements-to-maps`. This is useful when the conversion is to be applied to documents that are not part of the corpus, for example when new documents arrive for conversion every day and need to be converted in a consistent way. It also provides a more general mechanism for users to override the system decisions on what layouts to use for what elements.
The PR is not entirely complete at this stage: the technical detail is all there, but examples need to be reviewed. Comments are welcome at this stage.
There are a few other minor changes. The most notable are:
- More consistent fallback …
=> 1797 elements-to-maps-conversion-plan function

specifications/xpath-functions-40/src/function-catalog.xml
Fix #1704
The main substantive change is that unparsed-text() now explicitly discards any leading BOM.
Other functions that involve decoding of octets to strings are updated to reflect the changes that we made to reference the concept of "permitted characters".
=> 1704 Add rules/notes for BOM and related topics

specifications/xpath-functions-40/src/fos.xsd, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml
Adds the function `fn:binary-resource`
Also fixes some inconstencies in the handling of static/executable base URI in other resource access functions.
Fix #557
=> 557 Add fn:unparsed-binary function

specifications/xquery-40/src/query-prolog.xml
See issue #1954 
The PR removes the requirement for private variables and functions declared in library modules to be in the module namespace. There has never been any sensible reason for this restriction. 
The restriction is retained for public variables and functions; one could argue that it is unnecessary in that case also, but it does no harm and enforces good coding discipline.
=> 1954 (part) Private variables and functions don't need to be in the module namespace

specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/xslt.xml
By the simple expedient of adding 
```xml
<e:attribute name="*" required="yes">
<e:data-type name="expression"/>
</e:attribute>
```
to the syntax summary we get
With some additional prose, would that be sufficient?
=> Attempt to show that xsl:record allows extra attributes

specifications/xpath-functions-40/src/xpath-functions.xml
Replaces #1945 which was approved by the CG, but had pull conflicts because of incidental editorial changes
Fix #1568
=> 1568b Add unicode case-blind collation

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/expressions.xml
Fix #1661
See also #747
As discussed in the issue, I wasn't happy with the idea of changing the coercion rules to allow strings to be provided where a QName is expected, because of the need to keep the namespace context around at run-time, and because of potential confusion about exactly what namespace context is used.
Instead I have gone back to the idea of introducing QName literals, using the simple syntax #EQName.
Examples:
```
error(#err:XPTY0004)
node-name($node) = #xml:space
format-number($num, #de)
load-xquery-module($module)?variables?(#myvar)
transform({'initial-template':#xsl:initial-template})
{'last': 'Kay', 'first': 'Michael', 'suffix':#fn:null}
```
=> 1661 Introduce QName literals

specifications/xquery-40/src/expressions.xml
Fix #1240 
Fix #1972
This PR enables use of expressions such as `$rectangle?area() - sum($rectangle?contents()?area())` which would previously have failed with a type error.
=> 1240 Allow operand of dynamic function call to be a sequence

specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml
Fix #1985
Editorial.
The main effect is to centralise the descriptions of how to expand unprefixed QNames into a few named rules which can be referenced and reused throughout the spec.
=> 1985 Tidy up namespace terminology

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Does some general tidying up of the serialization text, but the main substantive changes are (a) to make HTML5 the default version, and (b) to make support for earlier versions effectively optional.
Please review carefully. Marking as editorial because I'm not sure any test cases need to change, but I might be wrong.
Fix #1889
=> 1889 Tidy up handling of HTML serialization version, default to HTML5

specifications/xquery-40/src/expressions.xml
Fix #1997
(A correction to an editorial error that made a substantive difference to the spec.)
=> 1997 Correct nesting of item coercion rules

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #1085
The new functionality introduced into the 4.0 version of fn:sort is repackaged into a new function fn:sort-by with a much cleaner interface; the fn:sort function reverts to its 3.1 specification.
If this PR attracts support then the corresponding change will be applied to the array:sort function.
=> 1085 Revert fn:sort to the 3.1 spec; introduce fn:sort-by

specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xpath-functions-40/style/merge-function-specs.xsl, specifications/xquery-40/src/expressions.xml
This PR adds six built-in named record types to the static context of every application:
Record [key-value-pair]
Record [load-xquery-module-record]
Record [parsed-csv-structure-record]
Record [random-number-generator-record]
Record [schema-type-record]
Record [uri-structure-record]
These are now listed in Appendix C of F&O
Issue 835 requests a review of the names of these records; perhaps putting them in one place will make that review easier. Personally, I am happy with the names as currently defined.
=> 835 Add built-in named record types to static context

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml
Fix #882
Supersedes PR #1883
There has been a great deal of discussion about the relative merits of the status-quo fn:chain function and the proposed replacement fn:compose. The CG was polled on whether it preferred to have fn:chain only, fn:compose only, or both, or neither. There was no clear consensus. The only option which no-one seemed to favour was to have fn:chain only -- which is the status quo. Since no-one is happy with the status quo I am therefore proposing that we drop this function. We can then start with a clean slate.
For the record the main criticisms of the fn:chain function as currently specified were:
(a) it is more useful to have a function that combines several functions into a single function, without actually applying that function to a set of supplied arguments …
=> 882 Drop fn:chain

specifications/xslt-40/src/element-catalog.xml, specifications/xslt-40/src/schema-for-xslt40.xsd, specifications/xslt-40/src/xslt.xml
Provides an XSLT package that uses named record types and methods to implement an atomic set data type, as an example of how abstract data types can now be implemented.
=> 1953 (part) XSLT Worked example using methods to implement atomic sets

specifications/grammar-40/xpath-grammar.xml
Today's merge of qt4cg/qtspecs#2028 has added the `MarkedNCName` production to both the XQuery and the XPath spec. It is however only used within the XQuery spec.
=> Hide `MarkedNCName` from XPath spec

specifications/xslt-40/src/xslt.xml
Fix #2009 
The rules for xsl:variable are changed so there is no attempt to construct an implicit temporary tree when the sequence constructor contains an `xsl:map`. `xsl:array`, or `xsl:select` instruction (perhaps mixed with other instructions).
Compatibility: note that `xsl:array` and `xsl:select` are new in 4.0, while xsl:map inside `xsl:variable` always throws an error in XSLT 3.0.
Justification: 
- a child `xsl:select` element behaves like a `select` attribute
- if the content of xsl:variable is `xsl:map` or `xsl:array` it makes no sense to require the user to add `as=map(*)` or `as=array(*)` because the type is obvious anyway.
=> 2009 Avoid constructing document node when it makes no sense

specifications/xpath-functions-40/src/function-catalog.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml
Closes #1970
Editorial. The only controversial change may be to rename the second parameter of `map:build` from `$keys` to `$key`.
=> 1970 Editorial notes

specifications/xpath-functions-40/src/function-catalog.xml
=> 2017 fn:sort-by: Observations

specifications/grammar-40/xpath-grammar.xml, specifications/image-sources/item-types.xml, specifications/xpath-datamodel-40/src/xpath-datamodel.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml, specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
This proposal (which has the JNodes proposal as its baseline) is a first cut at defining generalised steps and path expressions that handle both XNodes and JNodes in a uniform way.
The proposal adds functionality to path expressions (using "/") but does not yet remove the corresponding functionality from lookup expressions (using "?") - that will follow in a subsequent draft.
The changes are largely confined to XPath section §4.6. 
Obviously there is much scope to add notes and examples. There is also a need to reorganise sections so concepts are introduced before they are referenced.
=> 2054 Generalized Path Expressions

specifications/xpath-functions-40/src/function-catalog.xml
The `constructor` of `fn:schema-type-record` [is currently shown](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#schema-type-record) with a type of
```xquery
fn(xs:anyAtomicType?) as xs:anyAtomicType?
```
However this does not cover list type constructors, returning multiple occurrences. It should thus be
```xquery
fn(xs:anyAtomicType?) as xs:anyAtomicType*
```
A test exists that requires this: [`schema-type-005`](https://github.com/qt4cg/qt4tests/blob/79fd5cec8a8b15f9cad3f3d09045946f5bcab931/fn/schema-type.xml#L99-L116)
=> Fix type of `fn:schema-type-record` field `constructor`

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml
Renames the function `fn:jnode` as `fn:jtree`, and the item type `jnode-type()` as `jnode()`
Fix #2099
=> 2099 Rename fn:jnode and jnode-type

specifications/grammar-40/xpath-grammar.xml, specifications/xpath-functions-40/src/function-catalog.xml, specifications/xpath-functions-40/src/xpath-functions.xml, specifications/xquery-40/src/ebnf.xml, specifications/xquery-40/src/expressions.xml
The operators `<<` and `>>`, in my opinion, are poorly known, and challenging for developers working in XSLT. Many punctuation-based operators have aliases in ordinary-language quasi-equivalents, but `<<` and `>>` lack any ordinary verbal equivalents, and break this principle.
The attached proposal offers to make `precedes` a keyword equivalent to `<<` and `follows` a keyword equivalent to `>>`. This means that `//title[. &lt;&lt; following-sibling::isbn[1]]` can now be expressed as `//title[. precedes following-sibling::isbn[1]]`
=> Proposed new operator keywords: precedes, follows

specifications/xslt-40/src/xslt.xml
This PR simply moves the section on Patterns to a more logical place in the XSLT specification. Unless anyone objects, I will merge the PR without waiting for group approval, so that I can use the result as a baseline for further work on patterns and templates, hopefully giving a better diff baseline.
=> 2021 Move the section on Patterns to a more logical place in the spec

specifications/grammar-40/xpath-grammar.xml
The grammar rules for `StringTemplate` are as follows:
``` 
StringTemplate              ::=  "`" (StringTemplateFixedPart | StringTemplateVariablePart)* "`"
/* ws: explicit */
StringTemplateFixedPart     ::=  ((Char - ('{' | '}' | '`')) | "{{" | "}}" | "``")*
/* ws: explicit */
StringTemplateVariablePart  ::=  EnclosedExpr
/* ws: explicit */
``` 
But `StringTemplateFixedPart` should not be allowed as a zero-length token, because this is causing an ambiguity: the input ` `` ` currently can be parsed as any of
```xml
<StringTemplate>`<StringTemplateFixedPart/>`</StringTemplate>
``` 
```xml
<StringTemplate>`<StringTemplateFixedPart/><StringTemplateFixedPart/>`</StringTemplate>
``` 
```xml
<StringTemplate>`<StringTemplateFixedPart/><StringTemplateFixedPart/><StringTemplateFixedPart/>`</StringT …
```
=> Require at least one character in StringTemplateFixedPart

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml, specifications/xquery-40/src/query-prolog.xml, specifications/xslt-40/src/xslt.xml
Although issue #2143 envisaged redefining method calls in terms of JNodes, this PR takes a different approach.
The "magic" performed by the lookup operator when the entry in a map is annotated %method is dropped. Instead we have a new operator `?>` which is essentially defined as a macro: in simple cases `$map ?> method (X)` is defined to be essentially an abbreviation for `($map ? method)($map, X)`.
I have used the operator `?>` suggested by Christian, but in some ways I prefer the operator we had originally, `=?>`, because (a) there is a stronger analogy with `=>`, and (b) `?>` brings up images of XML syntax for processing instructions.
=> 2143 Redesign of method calls

specifications/xpath-functions-40/src/function-catalog.xml
In f2e1f48, `fn:parse-csv` was changed to return an empty sequence, when its first argument is an empty sequence. This is however not reflected in the function's return type, which is here changed to `parsed-csv-structure-record?`.
=> Fix return type in `fn:parse-csv` signature

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/expressions.xml
Proposed revision of the rules for get() in node tests.
Mainly editorial clarification; but also changes the rules for the focus - the expression is now evaluated with absent focus to ensure an error in preference to unexpected results.
Fix #2112
=> 2112 Refine/revise the rules for get() in node tests

specifications/grammar-40/xpath-grammar.xml, specifications/xquery-40/src/errors.xml, specifications/xquery-40/src/expressions.xml
The MethodAnnotation construct should have been dropped from the XPath grammar when we changed the mechanism for methods.
Fix #2173
=> 2173 Drop method annotations from XPath grammar

specifications/xquery-40/src/expressions.xml
Expands on the existing example as actioned in QT4CG-131-02 and QT4CG-131-03.
The example turned out to have rather more complexity than I imagined.
(Note, it unfortunately contains text that is replicated between the XPath and XQuery specs).
=> QT4CG-131-02 Expand on existing example for deconstructed variable bindings
