qt4cg/qtspecs

.circleci/config.yml
build.gradle

Just more infrastructure work.

Enable automatic builds at CircleCI

---

specifications/xslt-40/build.xml

Fix errors in stylesheet execution

---

build.gradle
etc/build-impl.xml

More build fixes

---

specifications/xslt-40/src/xslt.xml

A commit yesterday introduced a markup error.

Fix markup error introduced yesterday

---

.github/workflows/build-pr.yml
.github/workflows/build-specs.yml

This PR updates the github workflows so that all branches are published and so that the PR path is exposed in the environment.

Improve workflows

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/style/merge-function-specs.xsl

This is a re-application of Mike's PR onto the latest sources and build environment.

Mike's changes to fn:all and fn:some

---

specifications/xpath-functions-40/src/fos.xsd
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xpath-functions-40/style/merge-function-specs.xsl
specifications/xpath-functions-40/style/xpath-functions.xsl

Approved [on 27 September](https://qt4cg.org/meeting/minutes/2022/09-27.html)

Changes agreed 2022-09-20, and add history info to the spec for each function

---

specifications/xpath-functions-40/src/fos.xsd
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

and correct the fos.xsd schema for history/version information

New intersperse function now accepted

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/style/generate-keyword-test-set.xsl

This PR contains the editorial changes from #183 without the commits that add `fn:op` and other notes.
I believe I can fairly commit this PR without CG approval.

Editorial changes from PR 183

---

specifications/grammar-40/xpath-grammar.xml
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/expressions.xml

This PR is intended to be technically equivalent to #188.
I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them.

NW for MK: editorial (188)

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

This PR is intended to be technically equivalent to #173.
I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them.

NW for MK: fn:op (173)

---

specifications/xpath-functions-40/style/xpath-functions.xsl

Per MK's request. :-)
I also fixed the thing where the function names are too long and there was no space between the select elements!

Fix the function finder

---

specifications/grammar-40/xpath-grammar.xml

Fixes the broken typeswitch grammar pointed out in issue #41

Fix issue 41 (grammar bug in Typeswitch)

---

specifications/grammar-40/xpath-grammar.xml
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
specifications/xpath-functions-40/style/xpath-functions.xsl
specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/element-catalog.xml
specifications/xslt-40/src/xslt.xml

This PR is intended to be technically equivalent to #177.
I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them.

NW for MK: Items before, etc. (177)

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

This is another attempt to fix the merge conflicts in #222

Sequence comparison (starts, ends, contains) - issues 94, 96 (fix 222)

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Complete [actions](https://qt4cg.org/meeting/minutes/2022/11-15.html#new-actions) QT4CG-011-04 and QT4CG-011-05.

Updates to parse-uri and build-uri functions

---

specifications/xpath-functions-40/style/xpath-functions.xsl
style/xmlspec-2016.xsl

Next, move all the CSS into a common location

Give ednote a distinctive appearance

---

specifications/xpath-datamodel-40/src/changelog.xml
specifications/xpath-datamodel-40/src/namespace.xml
specifications/xpath-datamodel-40/src/xpath-datamodel.xml

This PR attempts to clean up some of the definitions of concepts in the data model spec, including fixing some minor errors.

Issue 225 - Data model clarifications

---

build.gradle
specifications/css/qtspecs.css
specifications/xpath-datamodel-40/style/data-model.xsl

I need to commit this first, and separately, so that the build will be correct.
Also fixed an obvious CSS typo.

Stylesheet updates for inline-SVG in the data model

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Add new function fn:items-at in response to issue 213

Issue 213: new function fn:items-at

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/expressions.xml

Actions QT4CG-011-01 and QT4CG-011-03. (Note, there are still some infrastructure problems with xnt references)

Actions QT4CG-011-01 and QT4CG-011-03. 

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

The function is symmetric with fn:index-where.

Issue #114 - add array:index-where() function

---

specifications/xslt-40/src/xslt.xml

PR #279 with merge conflicts resolved

---

specifications/xpath-functions-40/src/fos.xsd
specifications/xpath-functions-40/style/merge-function-specs.xsl
specifications/xpath-functions-40/style/xpath-functions.xsl

These are the schema and stylesheet changes from PR #292. They don't break the build and on casual inspection they seem fine, so I'm just going to accept them.

Mike's proposed schema and stylesheet changes

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Although discussion on issue #121 did not converge on a consensus, this PR proposes a new function which I believe meets the requirements expressed.

Proposed fn:char function - see issue 121

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml

Editorial change to fix a technical error in the data model spec (issue #18). Does not change the specification.

Fix issue #18 (function type hierarchy)

---

specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml

- Issue 300 (clarification about results being normalized)
- Action QT4CG-018-02 (explaining signature notation)
- Action QT4CG-018-04 (explaining numeric predicates on ancestor unions)

Minor editorial improvements

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

See https://github.com/qt4cg/qtsp…ecs/pull/304#issuecomment-1378532583 - but excluding item 3 because that's a stylesheet change.

Fix outstanding issues from PR 304

---

specifications/xquery-40/src/expressions.xml

This is a purely editorial change. Unless someone objects over the next few days, I'm just going to merge it in.

Add ednote per action QT4CG-016-02

---

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

Revises the rules for serializing meta elements to take account of new HTML5 syntax.
Resolves issue #318

Issue318 meta elements

---

specifications/xslt-40/src/xslt.xml

Drop obsolete note in XSLT regarding for-each-group/@array

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/element-catalog.xml
specifications/xslt-40/src/xslt.xml

Addresses issue #109 and issue #87. Unfortunately the PR also includes the unrelated commits for issue 22.

Issue109 xsl note

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Attempt to clarify fn:parse-uri and fn:build-uri

---

specifications/xpath-functions-40/src/function-catalog.xml

Note: I got a build failure trying to build this, it's doing DTD validation but there are invalidities, unrelated to the changes I made.

Proposal to add fallback behaviour to map:get and array:get

---

specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml

Improves termdef markup; adds error code; updates change history appendix.

Actions QT4CG-025-07 / -08

---

specifications/xpath-functions-40/src/xpath-functions.xml

Add compatibility notes for fn:namespace-uri-for-prefix

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Close #360 
This PR is the same as 360 but fixes merge conflicts.
Accepted at [meeting 027](https://qt4cg.org/meeting/minutes/2023/03-21.html#pr-360)
Close https://github.com/qt4cg/qtspecs/issues/314

MK PR #360 with merge conflicts resolved (array compositionand decomposition)

---

specifications/xpath-functions-40/src/function-catalog.xml

I reworked these (purely editorial) changes based on the current master to try and resolve the conflicts once and for all.

Rework changes from action-qt4cg-019-01 to resolve persistent conflicts.

---

specifications/xslt-40/src/xslt.xml

attribute namespace-uri corrected to namespace
xsl:sequence-of corrected to xsl:sequence

Fix syntax in examples

---

specifications/xpath-functions-40/src/function-catalog.xml

Fix #280
(Based off the right branch this time. I hope.)

Resolve #280 by allowing a fragid

---

specifications/xpath-functions-40/src/function-catalog.xml

Change fn:transform to use the stylesheet's default mode

---

specifications/css/xslt-40.css
specifications/xslt-40/style/xslt.xsl

Resolves action QT4CG-023-01, I believe. This is a minimal sort of fix, not an attempt to refactor everything.

Make XSLT function formatting consistent with F&O formatting

---

specifications/grammar-40/xpath-grammar.xml

Simple bug fix, shouldn't need any meeting time.

Fix bug #439 - grammar for ExprSingle

---

specifications/xpath-functions-40/src/xpath-functions.xml

Fix issue #86 (incorrect default timezone format)

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Resolves action item QT4CG-029-04.

fn:doc et al, error handling: inconsistencies. Closes #293

---

specifications/css/qtspecs.css
specifications/css/xpath-functions-40.css

Close #224 
Thanks @ChristianGruen for the reminder that this was still open!

Make code more visually distinct

---

specifications/xpath-functions-40/src/function-catalog.xml

Following review and acceptance of the parse-integer and format-integer functions, make changes suggested during the review. See actions QT4G-032-03 to -06.

Update parse-integer and format-integer following review

---

specifications/xpath-functions-40/src/function-catalog.xml

Supplemental examples related to pr #434 .

434: Added examples for parse-integer()

---

specifications/xquery-40/src/ebnf.xml

Add "otherwise" and thin arrow to the table. Editorial.

325 Update operator precedence table

---

specifications/xpath-functions-40/src/function-catalog.xml

Corrects errors in examples; changes other examples to make them testable. Further test failures remain to be investigated (some may be bugs in the Saxon implementation; others require improvements to the test generation mechanism).

Fix some errors in examples, as revealed by testing

---

specifications/xslt-40/src/xslt.xml

Fix typo, replace sequence-of with sequence

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/introduction.xml
specifications/xquery-40/src/mime-type.xml
specifications/xquery-40/src/query-examples.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xquery-40/src/xpath-backwards-compat.xml
specifications/xslt-40/src/xslt.xml
specifications/xslt-xquery-serialization-40/src/errors.xml

That was a work-intensive one, as expected, but I’m optimistic that the PR improves the overall situation.
I’ll be happy to see subsequent PRs if I missed something (e.g., I didn’t touch `ebnf.xml`).
Closes #471

471: <code> elements, simple/typographic quotes

---

specifications/xpath-functions-40/src/function-catalog.xml

Updates the spec of fn:load-query-module to handle functions with optional parameters. Resolves issue #526

526 load xquery module

---

specifications/xslt-xquery-serialization-40/src/errors.xml
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

The submitted edits are based upon a fresh reading of the serialization specs, and should all be relatively minor. Review would be appreciated, as small errors can have significant consequences.

Minor editorial edits

---

specifications/xpath-functions-40/src/function-catalog.xml

#361: Just an editorial one to get one more issue closed.

361: Named arguments: $input vs. $value

---

specifications/xpath-functions-40/src/fos.xsd

I can't explain why this didn't turn up initially in my local testing. :-(

Fix schema error

---

specifications/xpath-functions-40/src/function-catalog.xml

I know there are open comments on the actual spec, but in the short term, let's at least make the examples correct.

Fix examples to be consistent with spec

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

343: make $collation uniformly optional

---

specifications/xpath-functions-40/src/function-catalog.xml

This PR addresses some minor comments from issue #566. There are more substantive comments but I think they warrant discussion first.

Editorial fixes from #566

---

specifications/xquery-40/src/ebnf.xml

21: Revise appendix for reserved function names

---

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

This brief edit addresses issue #556, which I've chosen to handle apophatically.

Adjusted serialization step 5 note

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/expressions.xml

Allow element(A|B) and attribute(A|B)

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

* New function `fn:log`
* Rules of `fn:trace` revised

574: fn:log: Trace and discard results

---

specifications/grammar-40/xpath-grammar.xml
specifications/xpath-datamodel-40/src/element.xml
specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/mime-type.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/xslt.xml
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

See Matt’s comment in https://github.com/qt4cg/qtspecs/pull/533#issuecomment-1647945368

471: Quotes (missing cases)

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml

Per meeting today, made good on my comment in #546

414, 546: Adjusted XDM description of xs:string, added coding

---

specifications/css/xpath-datamodel-40.css
specifications/grammar-40/xpath-grammar.xml
specifications/xpath-datamodel-40/src/attribute.xml
specifications/xpath-datamodel-40/src/comment.xml
specifications/xpath-datamodel-40/src/dm-example.xsd
specifications/xpath-datamodel-40/src/document.xml
specifications/xpath-datamodel-40/src/element.xml
specifications/xpath-datamodel-40/src/namespace.xml
specifications/xpath-datamodel-40/src/processing-instruction.xml
specifications/xpath-datamodel-40/src/text.xml
specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-datamodel-40/style/data-model.xsl
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/schema-for-csv.xsd
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/introduction.xml
specifications/xquery-40/src/mime-type.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xquery-40/src/xquery-header.xml
specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/xslt.xml
specifications/xslt-xquery-serialization-40/src/errors.xml
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

Attempted revision in light of #624. Perhaps not everything is exactly right, but it should be a step in the right direction.

624: Adjusted function category descriptions

---

specifications/xpath-functions-40/src/function-catalog.xml

@ndw @michaelhkay I wonder what we should do with minor edits like this (which fixes an example)?
Should we merge them by ourselves, or wait for someone to approve and merge it?

508: Editorial, examples revised (array:split, array:slice, others)

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml

@ndw Should be ready to be merged

601: fn:all → fn:every?

---

specifications/xpath-functions-40/src/function-catalog.xml

665: Fix typos in fn:items-XX functions

---

specifications/xslt-40/src/xslt.xml

669 - fix typo "appearing appearing"

---

specifications/xpath-functions-40/src/function-catalog.xml

Completes action QT4CG-042-01 on NW.
There is a corresponding PR against the test suite.

Use sequences instead of arrays in fn:parse-uri output

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

@michaelhkay Again, some hints might need to be added for XPath (?).

36: fn:function-annotations

---

specifications/xpath-functions-40/src/xpath-functions.xml

668 define case insensitive collation normatively

---

tools/xhtml5.xsl

Maybe I'm more cleverer today than I was last time I looked into this.

Attempt to fix the problem with PRE elements in autodiffs

---

specifications/xslt-40/src/xslt.xml

Minor tweaks to the spec for capture=yes accumulator rules.
Fix #731

731 Capturing accumulators: Add error conditions, revise streaming rules

---

specifications/xslt-40/src/xslt.xml

QT4CG-048-03: Fix copy and paste errors in describing type patterns

---

specifications/xpath-functions-40/src/function-catalog.xml

768: details about decode-from-uri

---

build.gradle

Fix #776 
You'll need to pull and rebase `master` after I merge this.

Fix etc_XT40 output file

---

specifications/xquery-40/src/expressions.xml

695: Added xref to fn:slice()

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

I think this is sufficient to close issue 566. @ChristianGruen could you let me know if you agree?

566: Use fn:decode-from-uri in fn:parse-uri

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

801: non-deterministic → nondeterministic

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

651: fn:log → fn:message

---

specifications/xpath-functions-40/src/xpath-functions.xml

809 Move fn:atomic-equal to section 14.2

---

specifications/xpath-functions-40/src/function-catalog.xml

I don't really know how these crept in. Perhaps I was negligent in confirming that #828 passed tests in PR? Too late to tell now, but I think I've fixed them.

Fixed a couple of markup errors

---

specifications/xpath-functions-40/src/function-catalog.xml

838 Fix collation variable references

---

specifications/xpath-functions-40/src/function-catalog.xml

852 Fix typo in transitive-closure

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/function-catalog.xml

Editorial; closes #822 (visit this issue for a list of the changes)

822: XQuery, XQFO: Edits (pool)

---

.github/workflows/build-pr.yml

Trying to track down the spurious diffs that we see in PRs.
I'll have to merge this to test it, so there will be a few random merges here. Sorry.

Stop fussing with merge base branch

---

.github/workflows/build-pr.yml

Cleanup the post-diff-hacking hack

---

specifications/xslt-40/src/element-catalog.xml
specifications/xslt-40/src/xslt.xml

742 Drop xsl:function-library declaration

---

specifications/xpath-functions-40/src/xpath-functions.xml

867 Explain defaults in function signatures

---

specifications/xquery-40/src/expressions.xml

862 Add explanations and examples of implausible expressions

---

specifications/xquery-40/src/expressions.xml

887 - fix simple typo in example

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/expressions.xml

894 - errors in forming function items

---

specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml

In addition: Lexicographic order; formatting.

821 Annotations: Make default namespace explicit

---

specifications/xpath-functions-40/src/function-catalog.xml

XQFO: Minor edits

---

specifications/xquery-40/src/expressions.xml

915 function body terminology

---

specifications/xpath-functions-40/src/xpath-functions.xml

648 Disallow user modifications to schema for FN namespace

---

specifications/xpath-functions-40/src/function-catalog.xml

A duplicate name was introduced.

Fix the fo test catalog

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/xslt.xml

939 Remove fn:numeric-compare

---

specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/query-prolog.xml

Soem editorial clarifications regarding XQuery module import and schema import.
Fix #945

945 module import contradiction

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

970 XQFO: Context item → value

---

specifications/xquery-40/src/expressions.xml

Fix #966
Apply suggestions in Christian Grün's comments on PR #927.

966 Minor fixes to deep lookup 

---

specifications/xpath-functions-40/src/function-catalog.xml

628 Define result order for distinct-values and duplicate-values

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Issue: #843
Maybe we should keep the issue open after merging this PR.

843-partial Standard, array & map functions: Equivalencies

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

260 array:index-of

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

187 Add FLWOR expression while clause

---

specifications/xpath-functions-40/src/function-catalog.xml

Issue: #1009
I’ve used this PR to fix some other buggy examples in the XQFO spec.

1009 Examples, Return type of parse-json:fallback

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

655 fn:sort-with

---

specifications/xpath-functions-40/src/xpath-functions.xml

999 Allow comments in regular expressions

---

specifications/xpath-functions-40/src/function-catalog.xml

236 map:build: sequence of keys

---

specifications/xpath-functions-40/src/xpath-functions.xml

1054 Spec fn:message #id using old name fn:log

---

specifications/xpath-functions-40/src/function-catalog.xml

…an addendum to the editorial change I made yesterday; will be merged in a minute.

340-editorial fn:format-number

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

Fix #1082
Also adds some notes and examples

1082 Fix numeric literal grammar

---

specifications/xpath-functions-40/src/function-catalog.xml

XQFO (editorial)

---

specifications/xslt-40/src/xslt.xml

Changed the example to a book by a reputable author.
Fix #1079

1079 Change book used in example

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1089 Add rounding rules for casting string to duration etc

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

Proposes dropping "with" expressions from the spec.
Fix #1075

1075 Drop 'with' expressions

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/xslt.xml

Minor editorial fixes (examples, typos). I’ll merge this after a while if no one objects.

1060 Formatting

---

specifications/xpath-functions-40/src/function-catalog.xml

Whitespace, variable names, tests

1060 Minor fixes

---

specifications/xpath-functions-40/src/function-catalog.xml

1133 Correct map:filter callback signature

---

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

1118 Drop the "map" keyword in adaptive serialization output

---

specifications/xpath-functions-40/src/fos.xsd
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
specifications/xpath-functions-40/style/merge-function-specs.xsl

Close #1084 
This won't render correctly in the PR, but hopefully the diff is clear enough to decide if this is the approach we want to take.

1084 Add fos:default-description to support prose descriptions of defaults

---

specifications/xslt-40/src/xslt.xml

Fix error in XSLT example

---

specifications/xpath-datamodel-40/style/data-model.xsl
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xslt-40/style/xslt.xsl
style/xsl-query-2016.xsl

Use a common style for all glossaries. 
Add a glossary to F+O.
Fix #1155

1155 Consistency of glossaries

---

specifications/xquery-40/src/expressions.xml

1135 Correction to definition of focus functions

---

specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/conformance.xml
specifications/xquery-40/src/ebnf.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/introduction.xml
specifications/xquery-40/src/query-prolog.xml

There is more work to be done to ensure the change log entries are complete, but this is a good start.

1146 Add inline change markup in the XPath/XQuery spec

---

specifications/xpath-functions-40/src/function-catalog.xml

1173 array:build, map:build: Positional access

---

specifications/xpath-functions-40/src/function-catalog.xml

Return type changes from `xs:boolean` to `xs:boolean?`

1171 Change predicate callbacks to allow empty return value

---

specifications/xquery-40/src/expressions.xml

1143 Coercion rules: handle choice types before atomization

---

specifications/xpath-functions-40/src/function-catalog.xml

1188 XQFO hash

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

First draft of `fn:graphemes`, in response to discussion at #73 .
A battery of tests will be submitted as a PR to the qt4tests repository.

73 fn:graphemes

---

specifications/xpath-functions-40/src/function-catalog.xml

I'm not sure how this slipped past the PR build checks...

Fix ID/IDREF typo

---

specifications/xpath-functions-40/src/function-catalog.xml

1203 Define out-of-range conditions in CSV get function

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1196 Math Functions: math:e, math:sinh, math:cosh, math:tanh

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1195 Hash Function: CRC-32

---

specifications/xpath-functions-40/src/function-catalog.xml

1214 hash examples

---

specifications/xpath-functions-40/src/xpath-functions.xml

Minor: fixed URL

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/function-catalog.xml

1218 Drop use of union(A,B) syntax

---

specifications/xquery-40/src/ebnf.xml

1208 correct details of formerly-reserved function names

---

specifications/xslt-40/src/function-catalog.xml

Change required result of system-property(...version)

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/introduction.xml
specifications/xslt-40/src/xslt.xml
specifications/xslt-40/style/xslt.xsl
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
style/xmlspec-2016.xsl

1232 consistent rendition of rfc2119 terms

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1216 Detailed comments on math:e, sinh(), cosh(), tanh()

---

specifications/xpath-functions-40/src/function-catalog.xml

991 Fix editorial details in fn:invisible-xml

---

specifications/xpath-functions-40/src/function-catalog.xml

1187 Add midpoint-rounding option to fn:round()

---

specifications/xpath-functions-40/src/function-catalog.xml

305 Add options parameter for parse-xml and parse-xml-fragment

---

specifications/xpath-functions-40/src/function-catalog.xml

1246 Revert incompatibility in json-to-xml number formatting

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/ebnf.xml

1241 Add constraint to resolve node constructor ambiguity

---

specifications/xpath-functions-40/src/function-catalog.xml

1278 - line endings in unparsed-text-lines

---

specifications/xpath-functions-40/src/function-catalog.xml

1274 Further rounding modes

---

.github/workflows/build-specs.yml

This test will only work if I merge it, so ...

Attempt to rework how the test repository is updated

---

.github/workflows/build-specs.yml

Yes, it looks like that worked.

Commit the updated tests to the tests repository

---

style/xsl-query-2016.xsl

Changes stylesheet to handle case where a change log entry refers to multiple issues or PRs. See "Lookup Expressions" in XQuery for an example.

Stylesheet fix for 1298

---

specifications/xslt-40/src/xslt.xml

1253 whitespace in xsl:switch

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1287 Define parse-xml error conditions

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/expressions.xml

1161 Further revision of document-uri constraints

---

specifications/xslt-40/src/element-catalog.xml
specifications/xslt-40/src/xslt.xml

Revised PR that drops the proposed xsl:item instruction

46 Add @as attribute to xsl:sequence

---

specifications/xpath-functions-40/src/function-catalog.xml

Very minor editorial improvements.
Fix #1326

1326 wording improvements for concat and string-join

---

specifications/xpath-functions-40/src/function-catalog.xml

1329 Add content option to load-xquery-module

---

specifications/xpath-functions-40/src/fos.xsd
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xpath-functions-40/style/merge-function-specs.xsl
specifications/xpath-functions-40/style/xpath-functions.xsl
style/xsl-query-2016.xsl

Fix #1202
Since the changes are purely editorial but are likely to cause conflicts with technical changes, I would request an expedited review.

1202 Change Log for F&O spec

---

tools/autodiff.sh

Update version of DeltaXML

---

specifications/xpath-functions-40/src/xpath-functions.xml

1397 Add missing change log entry for constructor functions

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
specifications/xslt-40/src/xslt.xml

Rewrite of stylesheet for generating keyword tests

1368 built in keywords improvements

---

specifications/xslt-40/src/xslt.xml

1382 add error code XTSE4040

---

specifications/xquery-40/src/expressions.xml

1374 - allow static error for duplicate keys

---

specifications/xpath-functions-40/src/function-catalog.xml

Fix #1320 
(A speculative PR in the hope that my proposed resolution is acceptable.)

1320 Attempt to resolve a bug in parse-uri

---

specifications/xpath-functions-40/src/function-catalog.xml

Closes #1369
…no need to update any tests.

1369 fn:round: rounding-mode → mode

---

specifications/xpath-functions-40/src/function-catalog.xml

1346 Fix minor typos in format-number

---

specifications/xpath-functions-40/src/function-catalog.xml

1350 Fix signature for unparsed-text-available

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

959 fn:unix-time

---

specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/conformance.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml

1343 Drop the static typing feature

---

specifications/xquery-40/src/back-matter.xml

Close #1424 
Thank you, Amanda.

1424 Fix typo

---

specifications/xpath-datamodel-40/src/attribute.xml
specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml

Replace a few remaining occurrences of "atomic value" with "atomic item".

1337bis Replace a few remaining occurrences of "atomic value"

---

specifications/xquery-40/src/errors.xml

1408 Fix reference to "function conversion rules" in XPTY0117

---

specifications/xpath-functions-40/src/xpath-functions.xml

Fix typo in uri-structure-record

---

specifications/xpath-functions-40/src/function-catalog.xml

Fix #1426 (partially; it would also be good to have a better citation to IEEE 802.3)

1426 Add notes on endianness of CRC-32

---

specifications/css/qtspecs.css
specifications/xquery-40/src/ebnf.xml
style/grammar2spec.xsl
style/xmlspec-2016.xsl

Improves the presentation of grammar rules.
* Production numbers are dropped
* The width of the RHS column is increased so there is less line wrapping
* The summary EBNF is alphabetically sorted

1396 Improve presentation of grammar rules

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

1314 Change to type() syntax to fix ambiguity

---

specifications/xpath-functions-40/src/xpath-functions.xml

1372 Unknown option: FORG0013 → XPTY0004

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1446 Rephrase conformance rule on xs:dateTime limits

---

specifications/xpath-functions-40/src/xpath-functions.xml

Implement improvement to bibligraphy entry for IEEE 802.3

---

specifications/xpath-functions-40/src/function-catalog.xml

1322 fn:collation-available (editorial)

---

specifications/xpath-functions-40/src/function-catalog.xml

1373 XQFO: Editorial

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1427 Add element-number function

---

specifications/xpath-functions-40/src/function-catalog.xml

1422 fn:hash: Revision

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1421 fn:unix-time: Revisions

---

specifications/xquery-40/src/expressions.xml

1235 Function Identity: Treating function items with identical bodies

---

specifications/xpath-functions-40/src/function-catalog.xml

Fix typo in load-xquery-module example

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1325 Variadic System Functions limited to `fn:concat`

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/expressions.xml
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

1464 Standardize on "implementer" spelling

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1448 Component extraction on gregorian types

---

specifications/xpath-functions-40/style/merge-function-specs.xsl

1475 Stylesheet change to mark optional fields with '?'

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/ebnf.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xslt-40/src/xslt.xml

1450 Disallow reserved names in element/attribute constructors

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/ebnf.xml

Also updates the list of tokens using angle-brackets.
Fix #1312

1312 Add ws:explicit annotations

---

specifications/xpath-functions-40/src/function-catalog.xml

1308 In fn:apply, Correct $array to $arguments

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1483 return type of fn:error

---

specifications/xpath-functions-40/src/function-catalog.xml

1458 Arguments that have a default value but don't accept ()

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/ebnf.xml
specifications/xquery-40/src/expressions.xml

1512 Disallow reserved names in namespace and PI constructors

---

specifications/xquery-40/src/query-prolog.xml

1509 Drop obsolete/redundant text about "import schema" location hints

---

specifications/xpath-functions-40/src/function-catalog.xml

Corrects many of the errors in tests identified in issue #1516

1516(A) Fix failing F&O examples

---

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

1499 Deduplicate text relating to unused serialization parameters

---

specifications/xquery-40/src/expressions.xml

1525 Add notes on enumeration types

---

specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xslt-40/src/xslt.xml

Fix #1495 
Also corrects one or two broken cross-spec links.

1495 Drop context value static type

---

specifications/xquery-40/src/expressions.xml

Issue: #1318
Coercion rules added for maps and arrays.

1318 Function Coercion: Records, Maps, Arrays

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xslt-xquery-serialization-40/src/bibl.xml
specifications/xslt-xquery-serialization-40/src/schema-for-serialization-parameters.xsd
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

1471 JSON Serialization: json-lines

---

specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/xslt.xml

1500 New XSLT character-map() function

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml

1542 Add "formal" definitions of non-primitive axes

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml

1539 New civil-timezone function

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1563 Fix fn:schema-type examples

---

specifications/grammar-40/xpath-grammar.xml
specifications/xslt-40/src/xslt.xml

1522 Fix syntax ambiguity in patterns

---

specifications/xslt-40/src/element-catalog.xml
specifications/xslt-40/src/schema-for-xslt40.xsd
specifications/xslt-40/src/xslt.xml

1534 Allow xsl:result-document/@select

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1567 Supply missing change metadata

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/ebnf.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xslt-40/src/function-catalog.xml

1486 Editorial corrections & cleanups

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1555 change default for parse json escape

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml

689 fn:stack-trace: replace with $err:stack-trace

---

specifications/xslt-40/src/xslt.xml

Allow (some) self-references in global variables

---

specifications/xslt-40/src/xslt.xml

1449 Relax rules on multiple xsl:includes

---

build.gradle
specifications/css/xslt-40.css
specifications/js/xsl-datalist.js
specifications/xslt-40/style/xslt.xsl

Implement an instruction/function finder in XSLT

---

specifications/grammar-40/xpath-grammar.xml

Marks the relevant production rules as XQuery-only
Fix #1574

1574 Mark some productions as XQuery only

---

specifications/xpath-functions-40/src/function-catalog.xml

1595 Editorial

---

specifications/xslt-40/src/xslt.xml

1594 typos: dependant and repeated word

---

specifications/grammar-40/xpath-grammar.xml
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/expressions.xml

1593 Allow `document-node(NameTestUnion)`

---

specifications/xquery-40/src/expressions.xml

1598 $err:stack-trace: string, please

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/style/generate-qt3-test-set.xsl

Debugging output was accidentally left in place.

Drop diagnostic message from stylesheet

---

specifications/xpath-functions-40/src/function-catalog.xml

1605 csv-to-xml to return document node rather than element

---

specifications/xquery-40/src/expressions.xml

1625 Editorial changes to notes on path expressions

---

specifications/xpath-functions-40/src/function-catalog.xml

1637 Add/Amend notes to fn:function-lookup

---

specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/xslt.xml

1634 Update description of decimal properties in the static context

---

specifications/xpath-functions-40/src/function-catalog.xml

332 Add options for fn:path

---

specifications/xpath-functions-40/src/fos.xsd
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xpath-functions-40/style/merge-function-specs.xsl
specifications/xquery-40/src/expressions.xml

Various small copy edits.
Also adds summary descriptions to record definitions in the function catalog, which requires a schema and stylesheet change.

Minor copy edits (no issue raised)

---

specifications/xquery-40/src/expressions.xml

1678 Define element(E,T) and attribute(A,T) in terms of "derives-from"

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1261 New fn:divide-decimals() function

---

specifications/css/w3c-base.css

1681 - Delta marker in TOC

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1675 Fixes for CSV parsing

---

specifications/xslt-40/src/xslt.xml

1284 Define streamability of distinct-ordered-nodes

---

specifications/image-sources/anyAtomicType.xml
specifications/image-sources/anyType.xml
specifications/image-sources/item-types.xml
specifications/xslt-40/schema/xsltspec.dtd
specifications/xslt-40/src/xslt.xml

Added a few details to the type diagrams: user-defined array, map, and record types; enumeration types; untypedAtomic

1709 Updated type diagrams

---

specifications/js/fo-datalist.js
specifications/js/toc.js
specifications/js/xsl-datalist.js

This fixes 1747 so I'm going to push it immediately.
I'm leaving the bug open because I'll also look at @ChristianGruen 's report that it is problematic on mobile.

Fix 'window.onload' bug in ToC JS

---

specifications/EXPath/binary/src/function-catalog.xml

1792 Make function-catalog file schema-valid

---

specifications/xquery-40/src/expressions.xml

1807 Two exceptions to the rule, not three

---

specifications/xpath-functions-40/style/extract-sig.xsl
specifications/xpath-functions-40/style/xpath-functions.xsl

Brings F+O into line with the other specs.
Fix #1805

1805 Drop middle dots from termref rendition in F+O

---

style/xmlspec-2016.xsl

Drop "(Non-Normative)" from ToC

---

specifications/grammar-40/xpath-grammar.xml

1785 Fix two simple grammar bugs

---

specifications/xpath-functions-40/src/xpath-functions.xml

1788 Replace statement that maps are unordered

---

style/xmlspec-2016.xsl
style/xsl-query-2016.xsl

1827 Fix excess whitespace in TOC

---

.github/workflows/remove-label.yml

Action to remove label on reopen

---

specifications/grammar-40/xpath-grammar.xml

Fix grammar bug #1818

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1816 New function fn:partial-apply

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

583 Drop map:replace and array:replace

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

1834 Additional clarification on JSON lines

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xquery-40/src/expressions.xml

1815 Add more detail on annotations of function items

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

1829 Reintroduce restrictions on RHS of `=>`

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/ebnf.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml

1800 Methods

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

Fix #1456 
Technically identical to PR #1778, but reworked because it had become impossible to resolve the merge conflicts.

1456 Lookup expressions filtered by type

---

specifications/xpath-functions-40/src/function-catalog.xml

Tidies up the text and adds examples

Editorial revision of fn:function-identity

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

1866 Disambiguate TypeSpecifier syntax

---

specifications/xpath-functions-40/src/analyze-string.xsd
specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/xslt.xml

Incorporates and supersedes #1835

998 Add boundary and lookahead/behind assertions

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

1870 rename $zero keyword of fold functions

---

specifications/xquery-40/src/ebnf.xml

Update the table and explanatory notes.
Fix #1832

1832 Operator Associativity

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml

501 Error handling: try/finally

---

specifications/xpath-functions-40/src/function-catalog.xml

To follow: options for collection() and uri-collection().

1021 (part 1) Add $options arg to doc() and doc-available()

---

specifications/xquery-40/src/query-prolog.xml

1520 Allow forwards references to named item types

---

specifications/xpath-functions-40/src/function-catalog.xml

1876 In fn:replace(), merge the $replacement and $action parameters

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/xslt.xml

1905 Editorial edits

---

specifications/xpath-datamodel-40/src/xpath-datamodel.xml
specifications/xquery-40/src/expressions.xml

1896 Drop parameter names as a property of function items

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

Fix #1891
Fix #1799
partial fix for #1889

1891 clarifications on HTML versions and errors

---

specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml

1939 XQDY0153 (from try/finally) should be a type error

---

specifications/xslt-40/src/element-catalog.xml
specifications/xslt-40/src/schema-for-xslt40.xsd
specifications/xslt-40/src/xslt.xml

1725 xsl:mode/@copy-namespaces

---

specifications/xquery-40/src/expressions.xml

1907 method lookup (disallow wildcard selection)

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml

Purely editorial. No issue raised.

Add PR numbers and dates to change metadata

---

specifications/xslt-40/src/schema-for-xslt40.xsd

1943 Mark attributes with form=qualified

---

specifications/xpath-functions-40/src/function-catalog.xml

1958 Fix simple typo in map:build

---

specifications/xslt-40/src/schema-for-xslt40.xsd

Change to schema-for-xslt40
Fix #1957 (xsl:output disallow mixed content)
Add support for xsl:import-schema/@role

1957 xsl output allows mixed content

---

specifications/xpath-functions-40/src/function-catalog.xml

1967 r/binary-resource/unparsed-binary/

---

specifications/xpath-functions-40/src/function-catalog.xml

Change to use-xsi-schema-location (because the value is a boolean, not a location)
Fix #1952

1952 Change option name xsi-schema-location

---

specifications/xslt-40/src/schema-for-xslt40.xsd
specifications/xslt-40/src/xslt.xml

1951 Clarifications on serialization parameters

---

specifications/xquery-40/src/expressions.xml

1973 Cross-reference from type analysis to definition of disjointedness

---

specifications/xpath-functions-40/style/generate-keyword-test-set.xsl

1993 Stylesheet fix to copy the occurrence indicator

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/back-matter.xml
specifications/xquery-40/src/expressions.xml

1983 QName literals in node constructors

---

specifications/xquery-40/src/expressions.xml

1986 Drop obsolete notes on error reporting

---

specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/xslt.xml

2005 Add fn:apply-templates function

---

specifications/xslt-40/src/element-catalog.xml
specifications/xslt-40/src/xslt.xml

2004 Add xsl:select instruction

---

specifications/xquery-40/src/expressions.xml

Add rules for $V?$X

---

specifications/xslt-40/src/xslt.xml

2041 Correction to xsl:namespace-alias example

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

Redrafting of PR 1942, after discussion, and extension to XQuery
Fix #37 
Supersedes #1942 
This PR implements the decisions of today's discussion to the best of my understanding. I don't think further discussion is needed, but it does merit careful checking.

37 Sequence, Array, and Map destructuring

---

specifications/grammar-40/xpath-grammar.xml

2056 Implicit Whitespace in MarkedNCName and QNameLiteral

---

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

2059 Literal QNames: Adaptive serialization

---

specifications/xquery-40/src/query-prolog.xml

2040 Fix context value declaration issues

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

Allows conditional and repeated entries in a map constructor.
Fix #2003

2003 Generalize Map Constructors

---

specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/xslt.xml

2038 Tweak the rules for fn:apply-templates references to modes

---

specifications/xpath-functions-40/src/function-catalog.xml

2103 Allow operand of JNode accessors to be omitted or empty

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/expressions.xml

2098 Clarify when jnode() is called implicitly

---

specifications/css/xpath-functions-40.css

2066 CSS changes for function prototypes

---

specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml

2087 Change adaptive serialization of JNodes

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml

2157 Editorial updates to F+O §5.5 (Unicode collations)

---

specifications/xquery-40/src/expressions.xml

Expands on the let binding example

QT4CG-131-01/02 Expand on example as actioned

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml

1996 Lookups, KeySpecifier: Literal, ContextValueRef

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xquery-40/src/expressions.xml

Note: depends on #2115 because of terminology changes.
Fix #2132

2132 error handling in logical expressions

---

specifications/xpath-functions-40/src/function-catalog.xml

2100 Make innermost, outermost, has-children, path apply to JNodes

---

specifications/grammar-40/xpath-grammar.xml
specifications/xquery-40/src/expressions.xml
specifications/xquery-40/src/query-prolog.xml
specifications/xslt-40/src/xslt.xml

2163 Change ?> symbol to =?>

---

specifications/xquery-40/src/expressions.xml

2187 Add coercion rule for enumeration types

---

specifications/xpath-functions-40/src/function-catalog.xml
specifications/xpath-functions-40/src/xpath-functions.xml
specifications/xquery-40/src/ebnf.xml
specifications/xquery-40/src/expressions.xml
specifications/xslt-40/src/function-catalog.xml
specifications/xslt-40/src/schema-for-xslt40.xsd
specifications/xslt-40/src/xslt.xml

2075 Editorial Omnibus

---

specifications/xquery-40/src/errors.xml
specifications/xquery-40/src/expressions.xml

2196 Clarify XQST0070
